### ISSUE TITLE
Fix unnecessary bash-isms in installation-setup.sh

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#1000]
File `installation/installation-setup.sh` includes two unusually named functions:

- `json-glib_setup`
- `qemu-lite_setup`

These are both "bash-isms" since in traditional Bourne shell syntax, a function name cannot contain a dash (`-`).

We should rename the functions (using underscores) to be consistent with the other functions and to be "more Bourne-shell compatible".

**Comment by GabyCT** [comment]
I will do the necessary changes
