### ISSUE TITLE
Can't create more than 254 containers.

### ISSUE THREAD

**Issue by eadamsintel** [01org/cc-oci-runtime#1008]
When running density tests and creating multiple detached nginx or busybox containers I always get an error when trying to create the 255th container. 

docker run --runtime=cor -d nginx /bin/tail

[cc-oci-runtime.txt](https://github.com/01org/cc-oci-runtime/files/1098489/cc-oci-runtime.txt)

launch_time docker: Error response from daemon: shim error: open pid: no such file or directory.
Command exited with non-zero status 127

cc-oci-runtime version: 2.1.11
spec version: 1.0.0-rc1
commit: 1d8a1b94d6fce078320106889f767c847f01e6df

rroot@ccdemo2:/home/cc-demo/pnp# cat /proc/meminfo
MemTotal:       32833496 kB
MemFree:         3943128 kB
MemAvailable:    4201772 kB
Buffers:          126196 kB
Cached:           566444 kB
SwapCached:            0 kB
Active:         24278348 kB
Inactive:         353516 kB
Active(anon):   23961928 kB
Inactive(anon):   140968 kB
Active(file):     316420 kB
Inactive(file):   212548 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      33439740 kB
SwapFree:       33439740 kB
Dirty:                20 kB
Writeback:             0 kB
AnonPages:      23933276 kB
Mapped:           276944 kB
Shmem:            163668 kB
Slab:             727196 kB
SReclaimable:     204172 kB
SUnreclaim:       523024 kB
KernelStack:       84656 kB
PageTables:       156164 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    49856488 kB
Committed_AS:   631465592 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:  21164032 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      857568 kB
DirectMap2M:    29437952 kB
DirectMap1G:     3145728 kB

root@ccdemo2:/home/cc-demo/pnp# ls /proc/$(pgrep cc-proxy)/fd | wc -l
1021

root@ccdemo2:/proc# ls /proc/$(pgrep cc-shim)/fd | wc -l
12912

root@ccdemo2:/home/cc-demo/pnp# ls /proc/$(pgrep dockerd)/fd | wc -l
1537

**Comment by dlespiau** [comment]
Ah, excellent data. So the proxy hits the ulimit of opened file descriptors. We need to make that higher in the systemd service file!

**Comment by grahamwhaley** [comment]
Yep, that is the belief. We are trying that. Just getting the `LimitNOFILE=10000` into the correct `[Service]` section to test I believe...
If that pans out then we need to decide if we set a new limit in our default shipping service file, and we need to document this.

**Comment by eadamsintel** [comment]
Following Graham's advice I modified /usr/lib/systemd/system/cc-proxy.service and added in LimitNOFILE=10000 to the [Service] section and can now create more than 254 containers.

[Service]
ExecStart=/usr/libexec/cc-proxy
LimitNOFILE=10000

**Comment by dlespiau** [comment]
\o/ Fix proposal in PR #1009 :)
