### ISSUE TITLE
The Release key path in the Ubuntu Installation document is incorrect

### ISSUE THREAD

**Issue by danielscottt** [01org/cc-oci-runtime#1051]
The `curl` command [here](https://github.com/01org/cc-oci-runtime/blob/c2c185376b1449f47c3485d9a4b0f809880a80ac/documentation/Installing-Clear-Containers-on-Ubuntu.md#setup-the-repository-for-clear-container) is missing slashes in the request URL. It ought to look like this:
```bash
$ curl -fsSL http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-2.1/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
```

**Comment by dlespiau** [comment]
lgtm
