### ISSUE TITLE
3.0 Release Blog

### ISSUE THREAD

**Issue by amyleeland** [01org/cc-oci-runtime#1055]
We will need do a blog announcing our 3.0 release, with highlighted new architecture, features and a subset of our release notes.

**Comment by grahamwhaley** [comment]
@amyleeland , would this Issue be better located in https://github.com/clearcontainers/runtime maybe?

**Comment by grahamwhaley** [comment]
Replaced by https://github.com/clearcontainers/runtime/issues/425
