### ISSUE TITLE
Travis should call checkpatch to ensure correct formatting of changes.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#110]
As an example, see:
- https://github.com/01org/intel-cmt-cat/blob/master/.travis.yml

**Comment by grahamwhaley** [comment]
Looks good. Do we currently have the 'make style' target? And, we'll need to check that all the checking of checkpatch.pl from kernel.org is relevant to our 'style'. I think 90% of it will be.
From that link I could not see if it only checks on the most recent patches, or all patches in the repo etc. I guess that might be worked out in the 'style' target of the Makefile.

**Comment by jodh-intel** [comment]
No, we don't have the style target yet. This needs investigation and the link was just an example of how it could be done.
