### ISSUE TITLE
automate checking of Signed-off-by attestations

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#113]
Our policy is that all commits must have a developer attestation 'Signed-off-by' tag in them. Currently this is a manually checked process, and one day we will miss one no doubt. If possible we should try and automate checking for the tags. It is not clear if we can do this in the 'github status checks' or if we will do it in the Travis checks.
This might get handled by #110 , whereby the 'checkpatch.pl' will pick up the lack of Signed-off-by.

**Comment by jodh-intel** [comment]
This would also be handled by https://github.com/jodh-intel/cc-oci-runtime/tree/add-pullapprove-support since in that branch, `.pullapprove.yml` specifies:

```
signed_off_by:
  required: true
```

See http://docs.pullapprove.com/yaml/signed_off_by/

**Comment by jodh-intel** [comment]
We've now enabled pullapprove (see https://github.com/01org/cc-oci-runtime/wiki/Release-Process) which is now checking Signed-off-by.
