### ISSUE TITLE
Find a way to use the travis cache for our dependencies

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#114]
We should try to cache the building of glib/json-glib, they take the vast majority of our test time, making the cycle "change -> test" longer than necessary.

Simply enabling the cache (say caching /usr/local/) doesnss't seem to be enough at a glance, we have to detect if we do need to rebuild the cache (there isn't any cache or the versions of the deps we need are different than the one in the cache) or, if not, skip the whole dependency setup.

For that detection I'd simply copy versions.txt to the cache and compare it with the one in tree. If there's no versions.txt in the cache or if they are different, rebuild the cache. Skip rebuilding otherwise.

https://docs.travis-ci.com/user/caching/#Arbitrary-directories

**Comment by grahamwhaley** [comment]
Possibly relevant - I discussed the notion of ccache enabling on #65 . I still suspect that could save us a bunch of compile time?

**Comment by dlespiau** [comment]
Right, that'd be another possibility to look at, but caching the whole result of the "make install" should be even faster!

**Comment by dlespiau** [comment]
Let's garbage collect that one, the travis build is fast enough as is, no need to be overzealous.
