### ISSUE TITLE
"stop" isn't part of the OCI runtime spec anymore

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#117]
Looking at the spec history, I see that this command has been removed from the spec by: https://github.com/opencontainers/runtime-spec/pull/384.

Today stop and kill are aliased, I think we might just as well remove stop altogether.

Also runc doesn't have a stop command (anymore?)

**Comment by devimc** [comment]
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
