### ISSUE TITLE
docker can't run inside a clear-container

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#119]
I tried to run docker with runc as runtime backend on a clear-container and it was not possible. (This happens consistently on clearlinux docker image and ubuntu docker image)

Output with clearlinux container image:

root@5e8c8089a9c5 / # dockerd -D --storage-driver=vfs
DEBU[0000] Warning: could not change group /var/run/docker.sock to docker: open /etc/group: no such file or directory
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 647
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE
WARN[0000] containerd: low RLIMIT_NOFILE changing to max current=1024 max=4096
DEBU[0000] containerd: read past events count=0
DEBU[0000] containerd: supervisor running cpus=2 memory=2005 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[0001] Using default logging driver json-file
DEBU[0001] Golang's threads limit set to 14400
DEBU[0001] [graphdriver] trying provided driver "vfs"
DEBU[0001] Using graph driver vfs
DEBU[0001] Max Concurrent Downloads: 3
DEBU[0001] Max Concurrent Uploads: 5
DEBU[0001] Cleaning up old mountid : start.
FATA[0001] Error starting daemon: invalid argument

Output with ubuntu docker image:

root@833f2e0339eb:/# docker daemon -D --storage-driver=vfs
DEBU[0000] docker group found. gid: 110
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] previous instance of containerd still alive (4907)
DEBU[0000] containerd connection state change: CONNECTING
DEBU[0000] containerd connection state change: READY
DEBU[0000] received past containerd event: &types.Event
{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x57ad0377}
DEBU[0000] Using default logging driver json-file
DEBU[0000] Golang's threads limit set to 14400
DEBU[0000] [graphdriver] trying provided driver "vfs"
DEBU[0000] Using graph driver vfs
DEBU[0000] Cleaning up old mountid : start.
FATA[0000] Error starting daemon: invalid argument

Is this probably cause the cc-kernel does not support a feature that docker needs?

**Comment by mcastelino** [comment]
@sameo @jodh-intel @grahamwhaley @gorozco1 It may make sense to use a different kernel when container are run with --privileged
In that manner we can keep the kernel minimal except in the cases where the user chooses the --priv mode. It will mean we carry and extra kernel and maybe even a extra rootfs, but carry extra baggage for the normal case may not make sense.

**Comment by gorozco1** [comment]
@mcastelino @sameo IMHO if this is not a "production" feature or there is no bussines case for it I don't thing we should add it...
