### ISSUE TITLE
running functional tests make the host machine lose network configuration

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#123]
Host machine hangs when executing test 'start then kill (implicit signal)'. 

Steps to reproduce: 
run autogen:
 ./autogen.sh --with-qemu-path=/usr/bin/qemu-lite-system-x86_64 --with-tests-bundle-path=/root/mycontainer/ --with-cc-image=/usr/share/clear-containers/clear-containers.img --with-cc-kernel=/usr/share/clear-containers/vmlinux.container --enable-debug

run make:
 make -j 

run make check:
 make check

============================================================================
Testsuite summary for cc-oci-runtime 0.1
============================================================================
 TOTAL: 22
 PASS:  22
 SKIP:  0
 XFAIL: 0
 FAIL:  0
 XPASS: 0
 ERROR: 0
============================================================================
make[2]: Leaving directory '/root/cc-oci-runtime'
make[1]: Leaving directory '/root/cc-oci-runtime'
 ✓ cor -h
 ✓ cor exec -h
 ✓ cor kill -h
 ✓ cor list -h
 ✓ cor pause -h
 ✓ cor resume -h
 ✓ cor start -h
 ✓ cor state -h
 ✓ cor delete -h
 ✓ cor stop -h
 ✓ cor foo -h
 ✓ kill without container id
 ✗ kill with invalid container id
   (in test file tests/functional/kill.bats, line 27)
     `[[ "${output}" =~ "failed to parse json file:" ]]' failed
   Test logs: /tmp/tmp.6dCLcI3EKY-cor-test
   start then kill (implicit signal)

**Comment by chavafg** [comment]
After trying to reproduce locally,  @jcvenegas found that the issue is that the host machine is loosing the network when running the functional tests.

**Comment by jodh-intel** [comment]
This is also related to #93 - if you run `sudo unshare -n bats tests/functional/kill.bats` most of the kill tests work. Without the `unshare -n`, re-running the tests causes a storm of network errors if you run with `--debug --global-log ...`.

However, we should not require the functional tests to run as root, hence we need a way to disable network setup for this.

@mcastelino - could we just do something like:

```
if (getuid ()) {
   g_critical ("not running as root, so network setup disabled");
} else {
  cc_oci_network_create(config);
}
```

.. and run the tests in a new net ns?

**Comment by grahamwhaley** [comment]
Just pinging @mcastelino for feedback on @jodh-intel suggestion.

**Comment by jodh-intel** [comment]
Note that network setup is now disabled for non-root (see #216).

**Comment by chavafg** [comment]
any update on this?

**Comment by jodh-intel** [comment]
@jcvenegas - I think something like the following (totally untested :-) could work:

- Create `data/run-bats.sh.in` which will contain something like:
```
cmd="@BATS_PATH@"
[ $(id -u) -eq 0 ] && cmd="unshare -n $cmd"
eval "$cmd" $@
```
- Add `data/run-bats.sh.in` to the `GENERATED_FILES` list in `Makefile.am`.
- Update the `$(GENERATED_FILES)` rule to include expanding `@BATS_PATH@`.
- Add `data/run-bats.sh.in` to `EXTRA_DIST`.

**Comment by jcvenegas** [comment]
@jodh-intel  I think is a good idea, I've push  PR #319, could you take a look

**Comment by chavafg** [comment]
The above works for running the functional tests, but what about when running clear containers stand alone manually (without bats)? We still have the issue. Should I open a separate bug?

**Comment by jcvenegas** [comment]
@chavafg thats a good point, by now we can run bats test without problem , but for sure need to find a way to run cc-oci-runtime standalone as root. 

@jodh-intel  do you know if there is a way to detect we are running in a namespace or docker envirotment ?
