### ISSUE TITLE
Add CI to Pull Request

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#128]
Wee need a way to test on every PR safely, and notify the user that send the PR in case there are issues or tests broken.

**Comment by grahamwhaley** [comment]
I think this is directly related to #69 , yes?

**Comment by gorozco1** [comment]
@grahamwhaley yes, but is also to prevent and make sure a PR does not break tests, and if so, inform the owner of the PR, before the PR even pass for person to do code review.

**Comment by chavafg** [comment]
Currently I am setting a machine to launch VMs and test the build health. This will run unit and functional tests. Hope to get all the infrastructure and the triggers working next week.

**Comment by chavafg** [comment]
This can be considered done, we have a framework that executes tests on every PR (created and updated). 
Just adding some minor new features and fixes.
