### ISSUE TITLE
docker swarm mode fails on clearlinux host due to lack of ipvs

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#130]
The docker swarm native load balancer uses ipvs which is not enabled on clearlinux due to which cluster level load balancing fails.

```
Aug 17 18:14:41 clr-25b4453497364d64992a547e681bb36e dockerd[11739]: time="2016-08-17T18:14:41.779279502Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
Aug 17 18:14:41 clr-25b4453497364d64992a547e681bb36e dockerd[11739]: time="2016-08-17T18:14:41.778769553Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: WARNING: Module ip_vs not found in directory /lib/modules/4.7.0-253.native`, error: exit status 1"

```

To duplicate this issue

0. Stop all running containers just to be safe

      sudo docker rm -f $(sudo docker ps -a -q)

1. Make sure nginx works
      sudo docker run -d -p 8080:80 mcastelino/nginx

2. Check if it works
    curl localhost:8080 
    if that fails
    curl 127.0.0.1:8080

3. Remove the containers just to be safe
     sudo docker rm -f $(sudo docker ps -a -q)

Now setup swarm mode

1. sudo docker swarm init

2. sudo docker service create --name my_web --replicas 3 -p 8080:80 mcastelino/nginx

3. Check if they actually got started

    sudo docker service ls
    Note: you should see 3/3

    sudo docker ps
    Note: you should see 3 running docker containers

4. Check if you can reach the swarm
    curl localhost:8080    
    if that fails
    curl 127.0.0.1:8080

**Comment by gorozco1** [comment]
Do we need to add support for this on the container kernel or in the host kernel?

**Comment by mcastelino** [comment]
@gorozco1 host kernel only.

**Comment by miguelinux** [comment]
@mcastelino, @gorozco1 

IPVS modules will be shipped in the next Clear Linux release.

**Comment by miguelinux** [comment]
This issue will be solved in Clear Linux kernel release 4.7.1-257.native

**Comment by grahamwhaley** [comment]
I believe 4.7.1-257 is now available in Clear Linux 10030, which my swupd tells me is the latest on the server, so I think we can close this now - maybe after some QA?

**Comment by gorozco1** [comment]
yes, kernel is on 10030 now, we need to do verify it works properly first @chavafg

**Comment by gorozco1** [comment]
257 kernel is on image 10030 now..
