### ISSUE TITLE
Namespace cc-oci-runtime specific objects

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#131]
We should namespace our own things so we don't risk clashing what others are doing and future specs. So far I found:
- .containerexec inside the workload rootfs is quite generic. Maybe .cc-container-exec
- we have "private" variables in the OCI runtime state, they could do with some namespacing (and also follow the camelCase style used in the specs)

**Comment by devimc** [comment]
This issue was fixed when hyperstart was introduced to CC
https://github.com/clearcontainers/hyperstart/blob/master/src/init.c#L336
