### ISSUE TITLE
Size of terminal not updating

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#134]
Not resizing the terminal between the two commands, obviously!

```
$ docker run -t debian sh -c 'echo size = \(`tput cols`, `tput lines`\)'
size = (195, 52)
$ docker run --runtime cc -t debian sh -c 'echo size = \(`tput cols`, `tput lines`\)'
size = (80, 24)
```

The size of the terminal is updated within containerd-shim, but doesn't work with the way we hook things. Possibly related to #133.

**Comment by amyleeland** [comment]
Close this issue

**Comment by dlespiau** [comment]
Part of #374. Closing.
