### ISSUE TITLE
perl complains about the locale setup within the cc container

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#138]
For some reason we still have LANG set, probably leaking from the mini VM OS? and perl tells us loudly that we're doing something wrong.

```
$ sudo docker run debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=891d2fbed7e8
HOME=/root

$ sudo docker run debian /usr/bin/perl -e 'print "foo\n"'
foo
```

VS

```
$ sudo docker run --runtime cc debian env
container 3f7d1c16b086a22068493f6749fa975310612292b1497d2a731990b787760072 created
[    0.122995] systemd[1]: Failed to initialise default hostname
HOSTNAME=3f7d1c16b086
OLDPWD=/
TERM=vt220
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
PWD=/

$ sudo docker run --runtime cc debian /usr/bin/perl -e 'print "foo\n"'
container 171875989fe7194da2097f5de50ace6d9d0acad24f85cd2b5cc7f8bddc22cf35 created
[    0.069872] systemd[1]: Failed to initialise default hostname
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
foo
```

**Comment by grahamwhaley** [comment]
I'll add another example I hit around the same time, which I believe is caused by the same LANG issue.

Inside a CC docker (cor runtime), under an ubuntu image at least, If you run the caffe tests from here:
```
 https://github.com/BVLC/caffe
 http://caffe.berkeleyvision.org/install_apt.html
 http://caffe.berkeleyvision.org/installation.html#compilation
```

and:

```
cp Makefile.config.example to Makefile.config
#edit line 8 of Makefile.config to set CPU_ONLY
make all
make test
make runtest
```

then you will see (or I did) 177 failing test, all failing with:

```C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in SetUp().```

Under 'runc', all tests pass.

You can probably shortcut the download of the caffe sources etc. by using the docker hub image `kaixhin/caffe` which comes with the caffe github repo installed in the exec directory.

**Comment by dlespiau** [comment]
A quick test reveals that unsetting LANG does something good:
```
$ sudo docker run --runtime cc -e 'LANG=' debian /usr/bin/perl -e 'print "foo\n"'
container 64e43f391645192a067ba8faea21bd3eafa69aae5f5a3d0acfe5b5372ac6c932 created
foo
```

**Comment by grahamwhaley** [comment]
ooh, let me try that on the caffe tests.....

**Comment by grahamwhaley** [comment]
Odd. If I unset LANG, or 'LANG= make runtest' then I get a coredump in one of the tests. Seems to be somewhere in caffe::db::LMDB::Open() from the stack dump. That's going to need more investigation. Maybe another environment comparison between runc and cor.

**Comment by gorozco1** [comment]
This should be fixed when #324 is fixed

**Comment by gorozco1** [comment]
Remove the workaround here, make sure perl is not complaining when #324 is fixed

**Comment by dlespiau** [comment]
Closing this version of the bug in favour of #324
