### ISSUE TITLE
HOME isn't set in our default enviroment

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#139]
We should really provide what docker/runc have by default. Inevitably people will rely on this (say even in their Dockerfile). $HOME may well be treated in a special way because while it's not part of the 'env' section docker generates here:

```
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "HOSTNAME=0d280ea85f3f"
    ],
```

but running env in the container shows it set:

```
$ sudo docker run debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=891d2fbed7e8
HOME=/root
```

and we don't:

```
$ sudo docker run --runtime cc debian env
container 3f7d1c16b086a22068493f6749fa975310612292b1497d2a731990b787760072 created
[    0.122995] systemd[1]: Failed to initialise default hostname
HOSTNAME=3f7d1c16b086
OLDPWD=/
TERM=vt220
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
PWD=/
```

**Comment by dlespiau** [comment]
Another example from @mcastelino in #153 

> .In cc containers HOME is not setup. This may cause issues in some cases when programs or users make use of the same.
> 
> ```
> docker run -it --runtime=cor debian
> root@29bb76e40838:/# cd
> bash: cd: HOME not set
> ```

**Comment by jodh-intel** [comment]
Related - #183.

**Comment by amshinde** [comment]
runc checks if the HOME variable is set in the config.json, if not gets the HOME directory for the container user(from the user database of the workload) and sets that to the $HOME.  We could follow the approach and write it to .dockerenv for the workload to use it.
