### ISSUE TITLE
/tmp is shared between the workload process and the VM OS

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#144]
We could use PrivateTmp (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=) as a quick solution, but might as well take all the other init process/exec related issue and come up with a better solution.

**Comment by dlespiau** [comment]
This should be handled by hyperstart, revisit after we have hyperstart working

**Comment by dlespiau** [comment]
The goal is to make sure we don't see the VM /tmp from the container. Maybe just testing /tmp is empty would be enough as systemd would leave files in /tmp

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#16
