### ISSUE TITLE
Add a test ensuring the runtime doesn't write anything to stdout

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#146]
In issue #142, we had something written in stdout:

```
$ sudo docker run debian true
$ sudo docker run --runtime cc debian true
container 9cf769a030698323d01b9200b1b98c4d554fbe16435d3a6a0127484d7f18a120 created
$
```

We should have a way to easily create integration tests with docker (basically a test with the command above ensuring sdout/err is empty), preferably maintained in-tree.

**Comment by jodh-intel** [comment]
Docker tests were added under #181.
