### ISSUE TITLE
support linux.cgroupsPath and linux.resources (resource constraints)

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#148]
The OCI config file, `config.json`, specifies resource constraints in the form of `linux.resources` JSON objects which map closely to cgroups.

We need to find a way to implement such constraints.

See:
- https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#control-groups

**Comment by sameo** [comment]
Most of the resource constraints would need to be applied to the qemu process, a.k.a. the VM, by either using cgroups on the host or map the restrictions to qemu parameters (CPU, memory...).

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#19
