### ISSUE TITLE
cc-oci-runtime.sh fails to parse arguments

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#151]
When trying to use /usr/bin/cc-oci-runtime.sh to enable logs, I uncommented the next lines: 
```
# Uncomment to enable the global log which will persist after a Clear
# Container is destroyed.
runtime_args="$runtime_args --global-log=\"$global_log\""

# Uncomment to supplement the log with debug information
runtime_args="$runtime_args --debug"
```

but, when running cc-oci-runtime.sh I got some errors: 
```
root@clr-containers ~ # cc-oci-runtime.sh --list 
+ runtime=/usr/bin/cc-oci-runtime
+ global_log=/run/opencontainer/containers/cc-oci-runtime.log
+ runtime_args=
+ runtime_args=' --global-log="/run/opencontainer/containers/cc-oci-runtime.log"'
+ runtime_args=' --global-log="/run/opencontainer/containers/cc-oci-runtime.log" --debug'
+ exec /usr/bin/cc-oci-runtime ' --global-log="/run/opencontainer/containers/cc-oci-runtime.log" --debug' --list
no such command:  --global-log="/run/opencontainer/containers/cc-oci-runtime.log" --debug
```
Seems like the way it is parsing `runtime_args` is not working.

**Comment by jodh-intel** [comment]
I'm guessing you're using the clr packaged version of the runtime? This should work with the latest github code (which also now allows you to create a config file rather than modifying that script).

**Comment by chavafg** [comment]
@jodh-intel , right, it is the version packaged in clear linux. Will try latest github version and close if everything goes well.

**Comment by jodh-intel** [comment]
@chavafg - did using the latest github version work for you?

**Comment by jcvenegas** [comment]
It works for me

**Comment by chavafg** [comment]
closing this issue as it works with latest version.
