### ISSUE TITLE
Unit tests sometimes fail under Travis using clang

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#155]
The Travis run for #149 failed even though the branch only added a single `.yml` file. Further the failure only occured with `clang` (the `gcc` build was succesful). Restarting the `clang` Travis run resulted in a successful run.

We've seen this issue before so this issue attempts to capture what we know about the problem.

It looks like since I restarted the Travis run, the original logs are not available on the Travis site, but I have local copies.

The test which failed was `sh_vm_test`. Viewing the raw log showed that the problem seemed to be caused by the following unexpected errors:

```
realpath 'QEMU-LITE' failed: No such file or directory
realpath 'CLEAR-CONTAINERS.img' failed: No such file or directory
realpath 'CONTAINER-KERNEL' failed: No such file or directory
```

The failing test is `test_vm_handle_section()`, specifically the test on the file `./tests/data/vm.json`. That test tries to read the three files named above. All 3 files files should exist since they were created by `tests/test_common.c:test_spec_handler()`. That function doesn't abort if the files cannot be created, but it does display and error. But the Travis logs do not contain the file creation errors.

**Comment by jodh-intel** [comment]
Original Travis logs...

[log-clang.txt.gz](https://github.com/01org/cc-oci-runtime/files/431929/log-clang.txt.gz)
[log-gcc.txt.gz](https://github.com/01org/cc-oci-runtime/files/431931/log-gcc.txt.gz)

**Comment by dlespiau** [comment]
sounds like it could be an effect of the -j5 and we need to find a way to express a dependency on the creation of this vm.json file for sh_vm_test?

**Comment by dlespiau** [comment]
I haven't seen it happening since I changed the tests to run serially. Closing for now as it's travis only.

Please do re-open if encountered again.
