### ISSUE TITLE
obs packages for ubuntu don't correctly setup clear-containers.img

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#160]
For details, see my documented workaround in https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Ubuntu-16.04 (section "Modify the runtime configuration").

It looks like `vm.json` is not being expanded correctly as the packaged version contains `%{version}` in it, not the actual version.

**Comment by amshinde** [comment]
The last update to the image introduced a silly bug. I have pushed a fix.

**Comment by amshinde** [comment]
Can we close this?
