### ISSUE TITLE
obs packages should be provided by the clearlinux obs project

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#165]
Currently, the clearlinux obs packages are coming from...

- https://build.opensuse.org/project/show/home:amshinde

... but they need to be moved / recreated at:

- https://build.opensuse.org/project/show/home:clearlinux

Once that's happened, we need to:

1. update the wiki install pages:
  - https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Fedora-24
  - https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Ubuntu-16.04
1. post a message to the public mailing list (https://lists.01.org/mailman/listinfo/cc-devel) explaining how to update the existing Fedora/Ubuntu apt/yum/dnf repo files.

**Comment by amshinde** [comment]
jodh-intel Can you create a subproject "clear-containers-2.0" under home:clearlinux? I am afraid I dont have the right permissions to do that. I can create a project under home:clearlinux:preview, but I don't see that as the right place to put the new packages.

**Comment by jodh-intel** [comment]
Done: https://build.opensuse.org/project/show/home:clearlinux:preview:clear-containers-2.0

**Comment by amshinde** [comment]
I have sent submit requests to pull in the packages from my home project. jodh-intel you need to accept.

**Comment by jodh-intel** [comment]
Thanks @amshinde - packages accepted.

**Comment by amshinde** [comment]
jodh-intel you will need to add build targets for the project. I dont have permissions to do so.

**Comment by jodh-intel** [comment]
I'm not sure how to give you those perms as you are a "maintainer" for the project!?!

Meantime, I've created a selection of build targets.

**Comment by amshinde** [comment]
Sent mail to public mailing list. Closing this.
