### ISSUE TITLE
Implement "exec"

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#18]
The `exec` command is blocked on network support. Once networking is available, the function `clr_oci_vm_connect()` needs to be updated to remove the `g_critical ("not implemented yet")` call.

**Comment by devimc** [comment]
I took a look to current implementation of exec and I noticed that it uses ssh to connect to VM, this is a good approach but what will happen with minimal container images (busybox) that has not sshd ?

**Comment by gorozco1** [comment]
good catch @devimc, I think the ssh daemon will be provided by the mini-os when the clear-container is launched.

**Comment by gorozco1** [comment]
@devimc has some updates about this issue

**Comment by grahamwhaley** [comment]
now depends on #302

**Comment by dlespiau** [comment]
As part of this, we need to document that while the exec will work, the things people may use the exec function for (like manual networking setup) may not necessary work because it will be running inside of the VM.

**Comment by dlespiau** [comment]
Alright, time to close that one. Bugs found for exec should be opened as new issues (we've started already).
