### ISSUE TITLE
Add support for Centos/RHEL

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#182]
The runtime needs to be installable on Centos/RHEL.

**Comment by amshinde** [comment]
There are 2 issues:
qemu-lite doesnt compile on the gcc version that Centos provides. (gcc 5.0 is required for qem-lite, Centos comes with gcc-4.8.2-16)
You can find build failure logs for Centos  here: https://build.opensuse.org/package/live_build_log/home:amshinde/qemu-lite/CentOS_7/x86_64

The runtime has requirement for 2.46.2+ for the `G_FILE_MONITOR_WATCH_MOVES' flag
This requirement is not met either. Centos  comes with glib 2.42.2

**Comment by gorozco1** [comment]
@anthonyzxu do you have any comment here?

**Comment by jodh-intel** [comment]
Created a wiki page explaining how to install on Centos 7.2:

- https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Centos-7.2

**Comment by jodh-intel** [comment]
I think the instructions above are sufficient to allow basic testing on Centos. An optimisation is to bundle up those instructions into a dockerfile. Issue #198 raised to capture that idea.
