### ISSUE TITLE
namespaces are not created as specified by OCI spec

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#189]
The following namespaces are not honoured:
- `pid` (see #143).
- `mount`
- `ipc`
- `uts`
- `user`
- `cgroup`

See: https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#namespaces.

Note that the `network` namespace is created outside the VM - this is mandatory to work with docker and have working networking.

**Comment by jodh-intel** [comment]
Docker 1.12.1 specifies the following namespaces in `config.json`:

- `network` (done)
- `pid` (see #143)
- `mount`
- `uts`
- `ipc`

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#18
