### ISSUE TITLE
Networking: hostname specified in config.json not honoured.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#19]
Blocked on lack of network support.

See https://github.com/opencontainers/runtime-spec/blob/master/config.md#hostname

**Comment by mcastelino** [comment]
Should be fixed by #76

**Comment by dlespiau** [comment]
If we don't have a test for this, it'd be great to create one.

**Comment by jodh-intel** [comment]
+1. Maybe QA could add a new bats test?

**Comment by chavafg** [comment]
Verified and added a test to the functional docker+COR tests. Closing this issue as it is resolved.
