### ISSUE TITLE
Create Dockerfile to make using CC on Centos easier.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#198]
We now have https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Centos-7.2, but we could wrap that into a `Dockerfile` to make getting started even easier on this O/S.

**Comment by jodh-intel** [comment]
Note that care will need to be taken to ensure `linux-container` and `clear-containers.img` are updated reliably.

**Comment by devimc** [comment]
will be fixed in #673
