### ISSUE TITLE
the user and group settings in config.json are not honoured.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#20]
Specifically, `process.user.uid`, `process.user.gid` and `process.additionalGids` are ignored.

See:
-  `clr_oci_create_container_workload()` in [src/oci.c](src/oci.c).
- https://github.com/opencontainers/runtime-spec/blob/master/config.md#user.

**Comment by jodh-intel** [comment]
It would make sense to handle #139 here too.

**Comment by jodh-intel** [comment]
Although the default user+group are `root`, docker 1.12 specifies `process.additionalGids=10` (`wheel`).

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#17
