### ISSUE TITLE
Annotations are not exposed to the Clear Container.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#21]
See https://github.com/opencontainers/runtime-spec/blob/master/config.md#annotations.

**Comment by grahamwhaley** [comment]
More a bug than an enhancement or feature, as we have missing functionality. May need to raise priority depending on feature demands.

**Comment by amshinde** [comment]
I am not clear how annotations are going to be used by the container. A quick search through runc, shows that they are simply stored  and read bacc from the state file.

**Comment by jodh-intel** [comment]
The spec is not clear on how this data should be made available to the container so it would be interesting to see what `runc` does with it.

**Comment by devimc** [comment]
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
