### ISSUE TITLE
checkpoint and restore commands are stubs.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#22]

**Comment by grahamwhaley** [comment]
I've marked as bug, as this a missing feature that runc does have. Depending on need, we may wish to raise the priority of this. If anybody has more details and thoughts on possible implementations or potential stumbling blocks, please add them here.

**Comment by devimc** [comment]
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
