### ISSUE TITLE
Propagate and setup the full network config to the VM

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#220]
Right now we support only one network interface configured through the kernel command line. We need support for multiple interfaces, that is:
- Give the list of interfaces with their full configuration to the VM.
- Have _something_ applying that configuration to the VM.

**Comment by grahamwhaley** [comment]
Is this related to #68 ?

**Comment by amshinde** [comment]
Fixed in 2.1 branch

**Comment by chavafg** [comment]
@mcastelino , Can we also close this one, I think it is related to #94
Thanks

**Comment by mcastelino** [comment]
@chavafg yes. This too can be closed.

**Comment by chavafg** [comment]
Thanks, closing this issue
