### ISSUE TITLE
runtime should be regularly tested on top 100 docker hub images

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#226]
To provide a good level of confidence that the runtime works in all types of environments, we should consider running the full test suite on the top 100 docker images from https://hub.docker.com/explore/.

**Comment by dlespiau** [comment]
We already had a "QA" tag, so using that one instead. We could renamed QA to tests if you want though.

**Comment by GabyCT** [comment]
Closing this issue. The implementation is working currently in BAT for each release of clearlinux.
