### ISSUE TITLE
volumes: volume creation and mount fails on clear linux

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#23]
On clear linux I am unable to launch a container with an attached volume.
This failure is present both with runc and cors

docker-upstream run -it --runtime runc --name webxx -v /webappxx training/webapp python app.py
docker-upstream run -it runc --name webyy -v /webappyy training/webapp python app.py

Both these fail with the error
docker-upstream: An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=webxx: EOF.

The same command works on ubuntu

**Comment by grahamwhaley** [comment]
@mcastelino @jodh-intel So I think we need to decide if this is a CC

**Comment by jcvenegas** [comment]
@mcastelino 
The command:
docker run -it --runtime runc --name webxx -v /webappxx training/webapp python app.py

Does not break docker in Clear Linux version 9950,  It work with both cc-oci-runtime and runc.

**Comment by mrkz** [comment]
I'm also having this Issue using the `docker-cor` service on `clearlinux 10030`.
It mounts correctly the volume when using the **runc** runtime rather than **cc-oci-runtime**.

```
root@magneto ~ # docker run -v /etc/hostname:/root/hostname -it clearlinux                                            
docker: Error response from daemon: containerd: container not started.
root@magneto ~ # docker run --runtime runc -v /etc/hostname:/root/hostname -it clearlinux                             
root@e290fcf4814f / # cat /root/hostname 
magnetoroot@e290fcf4814f / # 
```

This is what I get from `# journalctl -f -u docker-cor`

```
Aug 19 14:34:10 magneto dockerd[27147]: time="2016-08-19T14:34:10.091458734Z" level=error msg="containerd: start container" error="containerd: container not started" id=9246c0c1bbf0856379b9a407662027280b440268ad3f731a0f876a798613e45f
Aug 19 14:34:10 magneto dockerd[27147]: time="2016-08-19T14:34:10.095181963Z" level=error msg="Create container failed with error: containerd: container not started"
Aug 19 14:34:10 magneto dockerd[27147]: time="2016-08-19T14:34:10.258256511Z" level=error msg="Handler for POST /v1.24/containers/9246c0c1bbf0856379b9a407662027280b440268ad3f731a0f876a798613e45f/start returned error: containerd: container not started"



Aug 19 14:34:24 magneto dockerd[27147]: time="2016-08-19T14:34:24.061972523Z" level=error msg="libcontainerd: failed to convert event timestamp: \"timestamp: nil Timestamp\""
```

First 3 lines of journalctl are from the failed 
`# docker run -v /etc/hostname:/root/hostname -it clearlinux `
while the last line is produced in journalctl is when running
` docker run --runtime runc -v /etc/hostname:/root/hostname -it clearlinux`

**Comment by jodh-intel** [comment]
@mrkz - thanks for the extra info. I can see now that the runtime assumes the "volume" is a directory, but clearly it doesn't have to be :-)

**Comment by jodh-intel** [comment]
To resolve this issue, the runtime needs to perform a check on the mount.source and if it's a regular file, create the specified mount.destination to allow the bind mount to succeed.

**Comment by jcvenegas** [comment]
I am PR for that
