### ISSUE TITLE
runtime command line option -d not parsed after [command] 

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#232]
Placing the '-d' option after the [command] on the command line can produce an 'Unknown option -d' error.

According to (implied by) the command line help, and the README.md file, you should be able to place the '-d' debug enable option anywhere on the command line. In reality, if we take the example from the running standalone section of the README.md:

`$ sudo ./cc-oci-runtime --log "$logfile" --log-format json create --bundle "$bundle_dir" --console $(tty) -d --pid-file "$pidfile" "$name"`

this produces the log output of:

`/usr/bin/cc-oci-runtime: create: Unknown option -d`

Thus, it looks like the '-d' is maybe being treated as a sub-command of 'create' rather than a standalone command. It feels like maybe a change in the command line parsing has had some subtle change in which options we handle in which order.

Moving the '-d' to the front of the command line works.

We should either fix the parsing, or fix the README.md and help to match the code.

**Comment by devimc** [comment]
same issue in runc , we should fix the README.md

```
runc --log=$(pwd)/log create -d --console $(tty) --bundle $(pwd)/bundle test
....
flag provided but not defined: -d
```
