### ISSUE TITLE
Missing cc-shim

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#234]
containerd-shim expects the workload/exec process left behind from the runtime to be a process on the very same host. Today we “fake” it by having telling containerd-shim that qemu is the workload process.

cc-shim would take qemu’s place to be a proxy to the real process inside the VM:
- get the stdout/err from cc-proxy and forward them onto cc-shim stdout/err
- get the stdin of cc-shim and pass it along to cc-proxy
- Exit status: get the exit status from cc-proxy and exits with it
- signals received by cc-shim need to be forwarded to the process inside the VM.

**Comment by dlespiau** [comment]
Ok, initial work is now merged. Further sizeable work should be tracked independently.
