### ISSUE TITLE
Missing cc-proxy

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#235]
The Clear Container proxy multiplexes the cc-shim commands and responses to the guest agent.

There is one single cc-proxy per host multiplexing all cc-shim into the guest agent. cc-proxy listens on AF_UNIX sockets from the cc-shim on one hand and on the guest agent serial ports on the other hand.

**Comment by gorozco1** [comment]
dummy question... can we change the tittle here for cc-proxy?

**Comment by grahamwhaley** [comment]
Then you'd also have to do #234 for cc-shim as well I think. Is it just for clarity @gorozco1 ? I see both cc-proxy and cc-shim are mentioned in the body of the Issue already.

**Comment by gorozco1** [comment]
@grahamwhaley @sameo yes thank you

**Comment by dlespiau** [comment]
Ok, the proxy has been merged. There's still work to be done, but we have started to capture the remaining things in separate issues. So closing this one.
