### ISSUE TITLE
Document hyperstart guest <-> host protocol

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#237]
Since we're going to use hyperstart as the guest agent, we need the protocol that it uses for communicating with the host.

**Comment by dlespiau** [comment]
The JSON commands are there: https://github.com/hyperhq/runv/tree/master/hyperstart/api/json

**Comment by dlespiau** [comment]
Upstream issue: https://github.com/hyperhq/hyperstart/issues/157

**Comment by jodh-intel** [comment]
@amshinde - would it make sense for you to take a look at this issue?

**Comment by laijs** [comment]
we are going to change the protocol of the streams for the hyperstart:
https://github.com/hyperhq/hyperstart/issues/182
any thought or recommendation?

**Comment by dlespiau** [comment]
Closing this bug. It's not related to the runtime. The upstream issue (hyperhq/hyperstart#157) should be enough to track it.
