### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#247]
We currently only support IPv4. We'll need to:
- Read the IPv6 config (IPs, routes, ...) from the private net ns
- propagate the config to the agent
- have the agent do the IPv6 setup

**Comment by grahamwhaley** [comment]
do you meann 'only support IPv4' ?

**Comment by dlespiau** [comment]
of course! :)

**Comment by devimc** [comment]
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
