### ISSUE TITLE
package hyperstart and include it in the mini-OS image

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#250]
We'd like to investigate hyperstart. Do do so without breaking what's working today, we need to package hyperstart and include a systemd unit file to start it.

Note: hyperstart is an init process, so the code assumes it needs to setup the system and so will fail to start as a simple daemon:

  - hyperstart tries to mount /dev, /proc, /sys, /dev/pts, ... and fail if they are already mounted.
  - there are various assumptions about the initrd image it currently uses: "/busybox" needs to exist as well as "/iptables"
  - it'll try to set the hostname
  - ...

Other things that will make the daemon fail:

   - hyperstart tries to open the 2 serial links to communicate with the host.
   - ...

Don't hesitate to edit this first comment to add more discoveries.

**Comment by dlespiau** [comment]
Just pushed a hyperstart branch that doesn't fail at startup and seems to do something:

  https://github.com/dlespiau/hyperstart/tree/20160912-daemon

Now it's time to try and talk to it. Of course, we also need to bring that up with upstream:

**Comment by jcvenegas** [comment]
Clear containers image now provides hypestart
