### ISSUE TITLE
Provide a mean to generate a suitable kernel for the mini-OS

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#251]
The end goal is being able to produce all the necessary components from this repo. Currently we maintain the kernel elsewhere and it'd be nice to build it as part of the build process.

A nice way to do this is to have a docker file doing it in a controlled environment: grab a base image (eg, a flavour of Debian/Fedora), get a well-known kernel version, apply some patches, make oldconfig with a config file we maintain in tree and output a suitable binary as the result of the process.

**Comment by jcvenegas** [comment]
Initial work in https://github.com/jcvenegas/osbuilder/commits/topic/init

**Comment by jcvenegas** [comment]
osbuilder scripts allow to build a kernel with clear-containers configuration
