### ISSUE TITLE
Provide a mean to generate the mini-OS

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#252]
The end goal is being able to produce all the necessary components from this repository. Currently we maintain the image elsewhere and it'd be nice to build it as part of the build process.

While there are many ways to create small OS images, we could use clear linux for the first of those.

A nice way to do this is to have a docker file doing it in a controlled environment and outputting the image as the result.

**Comment by jcvenegas** [comment]
Osbuilders scripts allow to create an image https://github.com/clearcontainers/osbuilder
