### ISSUE TITLE
Merge metric gathering hooks and code into the runtime repo

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#253]
We'd like to be able run the code that gather interesting metrics (the various boot stages, ...) into the runtime repo so developers can test the effect of their patches in place and ideally easily.

First step: ensuring all that is part of the repo, just like the docker tests atm.

I took a default assignee, please re-assign as needed. I also haven't put that task in the 2.1 milestone, not sure of its priority.

**Comment by chavafg** [comment]
I am reviewing the metric tests right now and they need some changes before I can add them to the repo.  Will upload them asap.

**Comment by dlespiau** [comment]
Thanks!

**Comment by chavafg** [comment]
created  https://github.com/01org/cc-oci-runtime/pull/314 to add metrics scripts

**Comment by dlespiau** [comment]
#314 has been merged closing this bug. Do reopen if needed.
