### ISSUE TITLE
Run all bundled tests on every PR raised.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#255]
Currently, Travis only runs the unit tests.

We need to find a way to run *all* the tests under Travis. However, we face a few problems:

- The newest Linux environment available under travis is Ubuntu Trusty (14.04).
- The Travis environment apparently does not provide VT-x support
  (since Google Compute Engine doesn't offer that - see https://github.com/travis-ci/travis-ci/issues/1419).

**Comment by dlespiau** [comment]
Adding to the 2.1 milestone, seems important enough to me we have that working during that time frame. Do yell if unhappy.

**Comment by jodh-intel** [comment]
thanks - I actually meant to do that at creation time but added the 2.1 backlog label erroneously ;)

**Comment by jodh-intel** [comment]
I've got 2 branches that attempt to solve this problem:

- https://github.com/jodh-intel/cc-oci-runtime/tree/run-functional-tests-in-travis

  This one tries to use only what Travis provides, but requires building gcc6 to allow the build of qemu-lite. The problem is that the gcc build take a looong time and generates a lot of output meaning Travis will fail the job.

- https://github.com/jodh-intel/cc-oci-runtime/tree/run-tests-in-travis-under-docker

  This branch uses a custom Docker image based on Fedora 24 that Travis can pull and run the runtime build and tests within. Whilst cleaner than the first branch, the generated build image is large (>1GB) and that may take some time to pull from within the Travis environment.

The problem with both branches though is that neither solve the issue (nor can they) that Travis doesn't offer VT-x support. Since Clear Containers are heavily reliant on kvm facilities (virtio, including 9p support), we cannot run the tests under Travis even using qemu emulation.

The only solution at this point seems to be to use an alternative to Travis (ideally bare metal) for running the functional tests.

**Comment by jodh-intel** [comment]
Adding Salvador to provide QA input.

**Comment by jodh-intel** [comment]
@chavafg - can this now be closed?

**Comment by chavafg** [comment]
Yes, now that we have CI testing (including functional tests) for all our PRs. Closing this issue.
