### ISSUE TITLE
Create a suitable bundle for functional tests

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#265]
RIght now we need to create a test bundle by hand for functional tests and provide its path to the configure script. We should create it as part of "make check" instead so we can:

  - automate its creation
  - have everyone testing with the same environment
  - control what goes in there for special testing (we could have binaries in that bundle we need to run to provide a testable output), eg. test signal forwarding to a process inside the VM.

**Comment by jodh-intel** [comment]
I'm already working on this as part of #255 - you cannot run the functional tests without a bundle so it's all part of it :-)
