### ISSUE TITLE
Handle updates required for OCI runtime version 1.0.0-rc2

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#275]
Handle any updates required to support OCI runtime specification 1.0.0-rc2:
- https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc2

**Comment by jodh-intel** [comment]
Requirements:

- [ ] Support `process.consoleSize` (#330).

**Comment by jodh-intel** [comment]
Once this has been implemented, we need to update the README (https://github.com/01org/cc-oci-runtime#supported-application-versions).

We might want to consider moving those details to the wiki in fact.

**Comment by dlespiau** [comment]
Do we want to strictly block on new (minor) features to support -rc2? we don't work with many of the -rc1 features. I think it's actually worse to not work at all rather than not just not honour process.consoleSize.

If we do work as well as with -rc1 with -rc2 by just saying we also support that version, how about just updating the code to not exit on -rc2? maybe not exit on any -rc?

**Comment by grahamwhaley** [comment]
Seeing discussion on #518, and in the discussion yesterday, I wondered if we should be less strict on the minor and -rc2 updates (patches) at least. And I'm more than happy if we start issuing a warning if the Docker version is > than the one we tested against, and even warnings for features in the json that we don't understand (we could distinguish between features we know but have/do not implement and new features that we have no clue about etc.)

**Comment by dlespiau** [comment]
I'd vote against loud warnings on stderr by default, we'd be spewing a lot of things at each invocation. A debug or "--strict" parameter could do that, but I'd push new features to 3.0

**Comment by jodh-intel** [comment]
PR #518 effectively fixes this issue since:

- The OCI spec specifies the versions be encoded in [SemVer](http://semver.org/spec/v2.0.0.html).
- SemVer specifies that as long as the Major versions are identical, Minor/Patch versions must be backwards compatible.

The runtime is careful to check the contents and format of `config.json` so although we do not currently support #330, once #518 lands we should now operate "more correctly" in line with the OCI spec by allowing the runtime to work with newer versions of docker that support a newer patch level of the OCI spec.

**Comment by jodh-intel** [comment]
We should be careful to continue to identify the latest version of container managers (such as docker) that we have tested with [1] as that will not necessarily match the latest available version.

---

[1] - https://github.com/01org/cc-oci-runtime#supported-application-versions

**Comment by dlespiau** [comment]
Ok, closing that one as well: as James said, #518 addresses the most important problem, and the  process.consoleSize support is tracked in its own bug.
