### ISSUE TITLE
create tests for networking code

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#280]
The following files do not have a unit test:
- `netlink.c`
- `network.c`
- `networking.c`

**Comment by jodh-intel** [comment]
Ideally, we also need functional and/or integration tests for networking (expand `tests/integration/docker/network.bats`).

Related: #94, #95, #220.

**Comment by egernst** [comment]
@GabyCT @jodh-intel  can this be closed?

**Comment by GabyCT** [comment]
closing this issue as network tests were added
