### ISSUE TITLE
Functional tests fail to run when using the default configuration

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#287]
When not giving any path to configure about where the test bundle is, it chooses `"$srcdir/tests/functional/bundle"` and that's the value used for the generation of common.bash. Unfortunately, this is a relative path and the tests fails, not being able to copy the bundle config.json:

```
 /bin/cp /home/damien/clear/sources/cc-oci-runtime/tests/functional/data/config-minimal-cc-oci.json ./tests/functional/bundle/config.json
   /bin/cp: cannot create regular file ‘./tests/functional/bundle/config.json’: No such file or directory
```

We can't use $abs_scdir in configure, but resolving the path in configure (for both the default value and the parameter given as path) sounds like the way to go to me.

**Comment by jodh-intel** [comment]
Fixed by #297.
