### ISSUE TITLE
Add support to read process.json provided by docker in exec command

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#298]
When docker exec is used the runtime get a json file that represents the process to be launched.

**Comment by jcvenegas** [comment]
Seems that this commit removes the json file that runc uses as process.json
https://github.com/opencontainers/runtime-spec/pull/388/commits/a7a366b334ccd28ceaf6821f7ccf462095df3212

**Comment by jcvenegas** [comment]
runc exec --proces option: https://github.com/opencontainers/runc/blob/master/exec.go#L54

**Comment by jcvenegas** [comment]
Related to #18

**Comment by jcvenegas** [comment]
Progress in  https://github.com/jcvenegas/cc-oci-runtime/tree/exec-process-json

**Comment by jcvenegas** [comment]
json privided by docker/containerd 
 {
  "terminal": true,
  "user": {
  },
  "args": [
  ],
  "env": [

  ],
  "cwd": "/",
  "capabilities": [
  ],
  "exec": true,
  "containerdStdin": "",
  "containerdStdout": "",
  "containerdStderr": "",
  "runtimeArgs": null,
  "noPivotRoot": false,
  "checkpoint": "",
  "rootUID": 0,
  "rootGID": 0
}

**Comment by jcvenegas** [comment]
process.json and oci process section does not contain the same sections but share some of them
section                 exec    process
terminal                [x]     [x]
user                      [x]     [x]
consoleSiz            [x]     [x]
cwd                       [x]     [x]
env                       [x]     [x]
args                     [x]     [x]
capabilities           [x]     [x]
rlimits                   [x]     [x]
apparmorProfile   [x]     [x]
selinuxLabel         [x]     [x]
noNewPrivileges  [x]     [x]
exec                    [x]     [ ]
containerdStdin   [x]     [ ]     
containerdStdou  [x]     [ ]
containerdStder   [x]     [ ]
runtimeArgs         [x]     [ ]     
noPivotRoot         [x]     [ ]     
checkpoint           [x]     [ ]     
rootUID                [x]     [ ]
rootGID               [x]     [ ]

**Comment by jcvenegas** [comment]
Adress this issue on #317

**Comment by gorozco1** [comment]
functional testing on #317

**Comment by dlespiau** [comment]
2.1 is now merged into master. Closing.
