### ISSUE TITLE
Modify “create” to start qemu and then pause when hyperstart is ready

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#299]
hyperstart sends a READY packet over CTL serial.

**Comment by dlespiau** [comment]
So, for that one, I chose the path where the proxy does that wait, the runtime has just to open the proxy socket and issue a "hello" command that will block until the READY has occurred.

https://github.com/dlespiau/cc-oci-runtime/tree/20160922-re-arch/proxy

**Comment by jodh-intel** [comment]
The main work items that the runtime needs to perform in "create" are:

1) launch `cc-shim` (passing proxy socket fd).
2) create state file (which contains the `cc-shim` pid).
3) run pre-start hooks (which reads the state file).
4) setup network (possible now since since a pre-start hook handles network i/f creation).
5) expand hypervisor arguments (including network options).
6) connect to `cc-proxy` (passing hyper agent socket details [from hypervisor arguments]).
7) launch hypervisor (which needs network and arguments).

The problem with the required ordering above is that there is a circular dependency:

- `cc-shim` requires the proxy socket fd.
- `cc-proxy` (indirectly) requires `cc-shim` to be running since:
   - the proxy needs (5).
   - (5) needs (4).
   - (4) needs (3).
   - (3) needs (2).
   - (2) needs (1).
   - (1) needs (6).

The best way to break this circular dependency is to modify the `cc-shim` launch code to do the following:

- create `shim_pipe`.
- `fork()`.
- perform blocking read on `shim_pipe`.

- parent creates state file
  This is awkward since although the workload pid will be correct, the hypervisor PID won't be and neither will the proxy details. However, the state file will contain the OCI-required values and thus should be considered valid by the hooks.
- << parent continues and eventually connects to `cc-proxy`>>
- parent connects to `cc-proxy`.
- parent sends `container_id` and `proxy_socket_fd` to `shim_pipe`.
- `cc-shim` child constructs `cc-shim` command-line args.
- `cc-shim` child exec's `cc-shim`.
- parent recreates the state file now that full information is available.

**Comment by grahamwhaley** [comment]
I've not stared at this really hard - I'd need to draw a picture I think :-) - but just a thought - could you maybe break the 'connect to cc-proxy' into two steps, so something like:
 0: connect to cc-proxy (but do not pass anything yet)
 1: launch shim, with fd from (0)
...
 6: now send details to proxy

could that break the '1 need 6' problem? Feels easier than an extra fork and pipe (but as I say, I've not thought it through, and you know the actual details better than I...)

**Comment by jodh-intel** [comment]
Yes, a picture would probably help :-)

Yep - I am actually mostly using the logic you've outlined above. The steps in my comment above were simplified - I didn't make it clear that the proxy connection is actually 2 calls: one to connect and the other to start communicating with the proxy. But you do need to fork as you cannot exec `cc-shim` from the child process until the proxy has confirmed that hyperstart is ready.

**Comment by jodh-intel** [comment]
This has been implemented in the `redesign-for-cc-2.1` branch as commit 4b101a914471b934112667bc68c5614abc697b42.

**Comment by dlespiau** [comment]
2.1 is now merged into master. Closing.
