### ISSUE TITLE
Modify "create" to do networking setup through hyperstart

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#301]
Replace the linux command line parameters we use today

**Comment by amshinde** [comment]
Considered the options available to setup network. One is systemd and the other with hyperstart. First one involves creating systemd network configuration units, but adds a dependency on systemd.

I've decided to do the network configuration with hyperstart protocol.The interfaces will configured to have predictable  PCI b/d/f addresses and the interfaces within the VM will be configured based on these predictable names using hyperstart SETUPINTERFACE command before the pod is created.

We also need to change the interface names within the VM to the ones docker has provided. Have sent out to PR for this.

**Comment by dlespiau** [comment]
2.1 is now merged into master. Closing.
