### ISSUE TITLE
Modify "start" to use hyperstart NEWCONTAINER command

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#302]

**Comment by dlespiau** [comment]
I think execcmd should be issued once the shim/proxy communication is already setup, so after https://github.com/01org/cc-oci-runtime/issues/303

**Comment by amshinde** [comment]
I don't think EXECCMD is needed. The STARTPOD command used earlier to set up the pod, starts the process in the container as well.

**Comment by dlespiau** [comment]
We still need to have the create/start split to match what OCI does, don't we? The idea was to do STARTPOD without the initial workload in "create", and do an EXECMD in "start"

**Comment by amshinde** [comment]
Well we could then simply start qemu in the create step and send the STARTPOD command in the start step. Else modify STARTPOD not to start the container process, but I doubt if that would be accepted upstream. (Note: runv does not support the OCI create command.)

**Comment by jcvenegas** [comment]
The flow to start a workload using EXECCMD is : 

STARTPOD->NEWCONTAINER->EXECCMD

The current flow would be 
runtime create -> STARTPOD without a container in the pod
runtime start -> Create a new container (NEWCONTAINER) exec initial workload (EXECCMD)

But NEWCONTAINER must provided the process information a workload (it can't be empty ), and then use EXECCMD for "exec" command. To allow to use "exec" before "start" @devimc  propose to create the container in the pod depending of which command is used first.

So if the runtime commands flow is "create" -> "exec" -> "start" , the exec command would create a new container in the pod using NEWCONTAINER hyper command and then when start is used will use EXECCMD.

**Comment by jcvenegas** [comment]
New PR into @jodh-intel branch to do NEWCONTAINER and do the initial workload:

https://github.com/jodh-intel/cc-oci-runtime/pull/10

**Comment by laijs** [comment]
we will NEWCONTAINER to CREATECONTAINER and STARTCONTAINER.

**Comment by jcvenegas** [comment]
start workload is launched using new container in #365

**Comment by jcvenegas** [comment]
fixed by #365
