### ISSUE TITLE
Modify "create" to spawn cc-shim

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#303]
`start` also needs to give `cc-shim`'s `pid` to `containerd-shim` and setup the proxy/shim communication.

**Comment by dlespiau** [comment]
The flow I have in mind at this point:

  - runtime opens proxy socket
  - runtime issues "hello" to proxy to associate to the connection to the right qemu/hyperstart instance
  - runtime receives an I/O socket from proxy (fd passing through unix socket)
  - runtime spawn cc-shim, giving it the proxy and I/O fds

**Comment by jodh-intel** [comment]
Assigning self as work on #299 covers some of the plan in @dlespiau's comment.

**Comment by amshinde** [comment]
jodh-intel  Is'nt the pid given to container-shim at the create step ?

**Comment by devimc** [comment]
almost merged https://github.com/01org/cc-oci-runtime/pull/365

**Comment by dlespiau** [comment]
2.1 is now merged into master. Closing.
