### ISSUE TITLE
Modify Travis build to make use of docker

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#305]
Travis is an excellent facility, but the fact that the newest environment they support is Ubuntu Trusty (14.04) is problematic given the old versions of tooling and libraries.

We should use Travis to trigger a build and test run inside a docker image since that way we can use any environment we wish (even multiple).

Related: #255, #295, #114, #155.

**Comment by jodh-intel** [comment]
Rework https://github.com/jodh-intel/cc-oci-runtime/blob/run-tests-in-travis-under-docker/ to only run unit tests (but including valgrind, cppcheck and code-coverage).

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#20
