### ISSUE TITLE
create a new container_agent.target

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#312]
New architecture use a different way to create and start initilal workload. Add a new containter.target to implement this new boot flow without break the current  implementation.

**Comment by jcvenegas** [comment]
Related to #303 #299

**Comment by dlespiau** [comment]
Isn't that somewhat done? do we have a way to start hyperstart only and not the initial workload?

**Comment by jcvenegas** [comment]
No, I did not take a look for a formal patch , just manually image modification to start hyperstart and do not mount shared rootfs ... I can convert that modifications to a PR today

**Comment by jcvenegas** [comment]
fixed by #373
