### ISSUE TITLE
docker run image sh hangs

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#316]
Running  "docker run debian sh" hangs, but docker run --runtime=runc exit directly

**Comment by jodh-intel** [comment]
This sounds like #17.

**Comment by gorozco1** [comment]
@jodh-intel I just made a comment in #17 , it seems to me that there are two issues in #17, this one is the second part of #17

**Comment by devimc** [comment]
#17 was fixed closing this issue
