### ISSUE TITLE
Error in mongo image

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#318]
Using the image of mongo from docker hub (docker pull mongo). It is not possible to start the database as it is showing us the next message
# docker run -ti mongo --auth

2016-10-07T12:47:03.095+0000 F CONTROL  [main] Failed global initialization: BadValue: Invalid or no user locale set. Please ensure LANG and/or LC_\* environment variables are set correctly.

**Comment by jodh-intel** [comment]
A workaround is to specify the value for `LANG` explicitly:

```
$ docker run --env LANG=C -ti mongo --auth
```

**Comment by grahamwhaley** [comment]
I expect this is also related to #138

**Comment by GabyCT** [comment]
Same behaviour happens at perl image
# docker run -ti perl perl -e 'print "Hello World\n"'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

**Comment by GabyCT** [comment]
I tested it using CC 2.1 and the error is still there 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.

**Comment by GabyCT** [comment]
Closing this issue as is working with clear-12860 image and CC 2.1. 
docker run -ti perl perl -e 'print "Hello World\n"'
Hello World
