### ISSUE TITLE
Rewrite clr_oci_expand_cmdline()

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#32]
In order to avoid the large number of `clr_oci_replace_string()` calls.

**Comment by devimc** [comment]
https://github.com/01org/cc-oci-runtime/pull/53/commits/31068d0f32d553df90d7fae03a49192c940f543c

**Comment by jcvenegas** [comment]
@devimc I like the new implementation, but it actually do the same number of calls  to clr_oci_replace_string

**Comment by devimc** [comment]
was fixed in https://github.com/01org/cc-oci-runtime/pull/53/commits/31068d0f32d553df90d7fae03a49192c940f543c ?

**Comment by devimc** [comment]
fixed in 31068d0
