### ISSUE TITLE
Error in drupal image

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#321]
It is not possible to start an instance using drupal image from docker hub (docker pull drupal).
1. docker run --name mysqlcontainertest -e MYSQL_ROOT_PASSWORD=secretword -e MYSQL_USER=test -e MYSQL_DATABASE=testdb -d mysql
2. docker run -ti --name containertest --link mysqlcontainertest:mysql -p 8080:8080 drupal
It is showing the following error
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
(1)Operation not permitted: AH00091: apache2: could not open error log file /var/log/apache2/error.log.
AH00015: Unable to open logs

**Comment by gorozco1** [comment]
@GabyCT works for me...

**Comment by grahamwhaley** [comment]
@gorozco1 Hi. You mean you run the same command and it has no errors for you?

So, we should now compare which versions of CC and distro we are running on I guess? :-)

**Comment by gorozco1** [comment]
@grahamwhaley yes.. my bad, I did not specify my version: Using clear 1820

**Comment by GabyCT** [comment]
We tried it with two different commits ids (8efc909698625fbdb6eb133ffe0f5094cd6dd151 and 13abb8b5b2e4661ade61e1cc5d19fae09252979e) and the error is still there. Clear version 10920.

**Comment by GabyCT** [comment]
The same error is happening for the image httpd.
# docker run -ti httpd apachectl -k start
(1)Operation not permitted: AH00091: httpd: could not open error log file /proc/self/fd/2.
AH00015: Unable to open logs

**Comment by GabyCT** [comment]
Using CC 2.1 the error is not there 
 # docker run -ti --name containertest --link mysqlcontainertest:mysql -p 8080:8080 drupal
[Fri Dec 02 21:12:31.501743 2016] [mpm_prefork:notice] [pid 3] AH00163: Apache/2.4.10 (Debian) PHP/7.0.13 configured -- resuming normal operations

**Comment by GabyCT** [comment]
Closing this issue as it is not present in cc 2.1
