### ISSUE TITLE
make distcheck not working properly

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#322]
make distcheck cannot find `tests/functional/common.bash`

```
...
47/48 files checked 97% done
Checking ../../src/util.c...
Checking ../../src/util.c: DEBUG...
48/48 files checked 100% done
(information) Cppcheck cannot find all the include files (use --check-config for details)
  GEN      tests/functional/common.bash
/bin/sh: line 1: tests/functional/common.bash: No such file or directory
make[1]: *** [Makefile:4628: tests/functional/common.bash] Error 1
make[1]: Leaving directory '/root/test/cc-oci-runtime/cc-oci-runtime-0.1/_build/sub'
make: *** [Makefile:4379: distcheck] Error 1
```

**Comment by dlespiau** [comment]
So, it's actually the change in how we generate certain files that break make distcheck. It boils down to us using sed to write the genrated files in $(srcdir) but in the general case, $(srcdir) has to be considered like a read-only directory, we always want to write in $(builddir).

This breaks the out of tree build that make distcheck does.
