### ISSUE TITLE
Ubuntu install no longer works

### ISSUE THREAD

**Issue by keenemaverick** [01org/cc-oci-runtime#328]
Following the instructions on https://github.com/01org/cc-oci-runtime/wiki/Installing-Clear-Containers-on-Ubuntu-16.04

At some point between last week and today, trying to run containers results in the error:

docker: Error response from daemon: containerd: container not started.

I see this result on multiple machines and VM's. I've tried re-installing from scratch with no luck either.

Attached is result of syslog after running "docker run ubuntu ls"
[syslog.txt](https://github.com/01org/cc-oci-runtime/files/530263/syslog.txt)

**Comment by gorozco1** [comment]
@keenemaverick thanks for reporting this issue we'll follow up on this ASAP

**Comment by ewa8949** [comment]
I also had the same issue on Ubuntu 16.04.  I did not do a clean install but this was working 2 weeks ago.  I don't believe this is related but I was getting clear containers to work on rkt and had compiled a stage1-kvm-qemu.aci image.  

Here is the relevant portion of my syslog.txt

Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.697197268-07:00" level=debug msg="Calling POST /v1.24/containers/create"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.697413787-07:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"bash\"],\"Dom
ainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOp
s\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\
"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IO
MaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\
":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"Read
onlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"Runtime\":\"cor\",\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":
\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"ubuntu\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"StdinOnce\":true,\"Tty\":true,\"User\":\"
\",\"Volumes\":{},\"WorkingDir\":\"\"}"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.698389130-07:00" level=debug msg="devmapper: AddDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init baseh
ash=e9d866ccdf2e7f4f2be22b338d2925cbb8223b6c2445bc379169037fad0382f3)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.700345354-07:00" level=debug msg="devmapper: registerDevice(395, 7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init)
"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.701153831-07:00" level=debug msg="devmapper: AddDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init baseh
ash=e9d866ccdf2e7f4f2be22b338d2925cbb8223b6c2445bc379169037fad0382f3) END"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.701613490-07:00" level=debug msg="devmapper: activateDeviceIfNeeded(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-in
it)"
Oct 14 09:18:43 eadams-linux systemd[2508]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appe
ared twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux systemd[1]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appeare
d twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.733257991-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.733283300-07:00" level=debug msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/7031bf383f6dc8f64bf0823d503de79a7076d2823f9732394
2a8d4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux kernel: [ 2222.787295] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.762720447-07:00" level=debug msg="devmapper: Unmount done"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.762752684-07:00" level=debug msg="devmapper: deactivateDevice(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.762794715-07:00" level=debug msg="devmapper: removeDevice START(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a
8d4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.811088482-07:00" level=debug msg="devmapper: removeDevice END(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d
4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.811120091-07:00" level=debug msg="devmapper: deactivateDevice END(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init
)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.811129188-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init)
END"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.811138964-07:00" level=debug msg="devmapper: AddDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d basehash=7
031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.813070270-07:00" level=debug msg="devmapper: registerDevice(396, 7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.813891352-07:00" level=debug msg="devmapper: AddDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d basehash=7
031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d-init) END"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.815963915-07:00" level=debug msg="devmapper: activateDeviceIfNeeded(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux systemd[2508]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appe
ared twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux systemd[1]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appeare
d twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.849791203-07:00" level=debug msg="container mounted via layerStore: /var/lib/docker/devicemapper/mnt/7031bf383f6dc8f64bf0823d503de79a70
76d2823f97323942a8d4a8ab7b930d/rootfs"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.849834805-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.849853418-07:00" level=debug msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/7031bf383f6dc8f64bf0823d503de79a7076d2823f9732394
2a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux kernel: [ 2222.903302] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.880286330-07:00" level=debug msg="devmapper: Unmount done"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.880316482-07:00" level=debug msg="devmapper: deactivateDevice(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.880361576-07:00" level=debug msg="devmapper: removeDevice START(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a
8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.927043492-07:00" level=debug msg="devmapper: removeDevice END(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d
4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.927072760-07:00" level=debug msg="devmapper: deactivateDevice END(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.927081522-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d) END"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.928683068-07:00" level=debug msg="Calling POST /v1.24/containers/93bdc16c1651781537fc68e74b89820b7c81c082cab03e52ad4bc5830137c752/attac
h?stderr=1&stdin=1&stdout=1&stream=1"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.928772677-07:00" level=debug msg="attach: stdin: begin"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.928805490-07:00" level=debug msg="attach: stdout: begin"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.928830533-07:00" level=debug msg="attach: stderr: begin"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.929002888-07:00" level=debug msg="Calling POST /v1.24/containers/93bdc16c1651781537fc68e74b89820b7c81c082cab03e52ad4bc5830137c752/start
"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.929394495-07:00" level=debug msg="devmapper: activateDeviceIfNeeded(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:43 eadams-linux systemd[1]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appeare
d twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux systemd[2508]: dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device: Dev dev-disk-by\x2duuid-18a32a78\x2da31c\x2d4d36\x2dacde\x2db0b409332e31.device appe
ared twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-1
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.956185564-07:00" level=debug msg="container mounted via layerStore: /var/lib/docker/devicemapper/mnt/7031bf383f6dc8f64bf0823d503de79a70
76d2823f97323942a8d4a8ab7b930d/rootfs"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.956283186-07:00" level=debug msg="Assigning addresses for endpoint admiring_mayer's interface on network bridge"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.956304728-07:00" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Oct 14 09:18:43 eadams-linux systemd-udevd[11748]: Could not generate persistent MAC address for veth334960f: No such file or directory
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <warn>  [1476461923.9575] device (veth636533e): failed to find device 49 'veth636533e' with udev
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.957567473-07:00" level=debug msg="Assigning addresses for endpoint admiring_mayer's interface on network bridge"
Oct 14 09:18:43 eadams-linux systemd-udevd[11747]: Could not generate persistent MAC address for veth636533e: No such file or directory
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9583] manager: (veth636533e): new Veth device (/org/freedesktop/NetworkManager/Devices/41)
Oct 14 09:18:43 eadams-linux kernel: [ 2223.010757] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Oct 14 09:18:43 eadams-linux kernel: [ 2223.011668] docker0: port 1(veth334960f) entered blocking state
Oct 14 09:18:43 eadams-linux kernel: [ 2223.011670] docker0: port 1(veth334960f) entered disabled state
Oct 14 09:18:43 eadams-linux kernel: [ 2223.011718] device veth334960f entered promiscuous mode
Oct 14 09:18:43 eadams-linux kernel: [ 2223.011781] IPv6: ADDRCONF(NETDEV_UP): veth334960f: link is not ready
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <warn>  [1476461923.9587] device (veth334960f): failed to find device 50 'veth334960f' with udev
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.958780540-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.958804842-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9594] manager: (veth334960f): new Veth device (/org/freedesktop/NetworkManager/Devices/42)
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.960771207-07:00" level=debug msg="Programming external connectivity on endpoint admiring_mayer (1854ffae41c07274d68e01d7c9a8255c74f06afa806f27bfd7f14d186f04fc6c)"
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9639] devices added (path: /sys/devices/virtual/net/veth636533e, iface: veth636533e)
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9639] device added (path: /sys/devices/virtual/net/veth636533e, iface: veth636533e): no ifupdown configuration found.
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9688] devices added (path: /sys/devices/virtual/net/veth334960f, iface: veth334960f)
Oct 14 09:18:43 eadams-linux NetworkManager[831]: <info>  [1476461923.9688] device added (path: /sys/devices/virtual/net/veth334960f, iface: veth334960f): no ifupdown configuration found.
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.998042424-07:00" level=error msg="containerd: start container" error="containerd: container not started" id=93bdc16c1651781537fc68e74b89820b7c81c082cab03e52ad4bc5830137c752
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.999684439-07:00" level=error msg="Create container failed with error: containerd: container not started"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.999722774-07:00" level=debug msg="attach: stdout: end"
Oct 14 09:18:43 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.999739147-07:00" level=debug msg="attach: stdin: end"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.999902694-07:00" level=debug msg="attach: stderr: end"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:43.999953915-07:00" level=debug msg="Closing buffered stdin pipe"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.000922519-07:00" level=debug msg="Revoking external connectivity on endpoint admiring_mayer (1854ffae41c07274d68e01d7c9a8255c74f06afa806f27bfd7f14d186f04fc6c)"
Oct 14 09:18:44 eadams-linux kernel: [ 2223.056674] docker0: port 1(veth334960f) entered disabled state
Oct 14 09:18:44 eadams-linux kernel: [ 2223.058176] device veth334960f left promiscuous mode
Oct 14 09:18:44 eadams-linux kernel: [ 2223.058178] docker0: port 1(veth334960f) entered disabled state
Oct 14 09:18:44 eadams-linux libvirtd[1032]: ethtool ioctl error: No such device
Oct 14 09:18:44 eadams-linux NetworkManager[831]: <info>  [1476461924.0235] devices removed (path: /sys/devices/virtual/net/veth636533e, iface: veth636533e)
Oct 14 09:18:44 eadams-linux NetworkManager[831]: <info>  [1476461924.0235] device (veth636533e): driver 'veth' does not support carrier detection.
Oct 14 09:18:44 eadams-linux NetworkManager[831]: <info>  [1476461924.0237] device (veth334960f): driver 'veth' does not support carrier detection.
Oct 14 09:18:44 eadams-linux NetworkManager[831]: <info>  [1476461924.0249] devices removed (path: /sys/devices/virtual/net/veth334960f, iface: veth334960f)
Oct 14 09:18:44 eadams-linux libvirtd[1032]: ethtool ioctl error: No such device
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.067641570-07:00" level=debug msg="Releasing addresses for endpoint admiring_mayer's interface on network bridge"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.067671651-07:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Oct 14 09:18:44 eadams-linux libvirtd[1032]: ethtool ioctl error: No such device
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.087045926-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.087079912-07:00" level=debug msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux libvirtd[1032]: ethtool ioctl error: No such device
Oct 14 09:18:44 eadams-linux libvirtd[1032]: ethtool ioctl error: No such device
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.110002048-07:00" level=debug msg="devmapper: Unmount done"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.110023155-07:00" level=debug msg="devmapper: deactivateDevice(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.110068880-07:00" level=debug msg="devmapper: removeDevice START(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux libvirtd[1032]: Failed to open file '/sys/class/net/veth334960f/operstate': No such file or directory
Oct 14 09:18:44 eadams-linux libvirtd[1032]: unable to read: /sys/class/net/veth334960f/operstate: No such file or directory
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.163082168-07:00" level=debug msg="devmapper: removeDevice END(docker-8:6-27269333-7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.163111657-07:00" level=debug msg="devmapper: deactivateDevice END(7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d)"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.163120919-07:00" level=debug msg="devmapper: UnmountDevice(hash=7031bf383f6dc8f64bf0823d503de79a7076d2823f97323942a8d4a8ab7b930d) END"
Oct 14 09:18:44 eadams-linux dockerd[8155]: time="2016-10-14T09:18:44.163193224-07:00" level=error msg="Handler for POST /v1.24/containers/93bdc16c1651781537fc68e74b89820b7c81c082cab03e52ad4bc5830137c752/start returned error: containerd: container not started"

**Comment by gorozco1** [comment]
External packages of clear-containers has not been updated recently this looks more like a compatibility issue between ubuntu's docker version:

**Ubuntu 16.04 docker versions:**

```
$ docker-runc --version
runc version 1.0.0-rc2
commit: 02f8fa7863dd3f82909a73e2061897828460d52f
spec: 1.0.0-rc2-dev

$ docker-containerd --version
containerd version 0.2.4 commit: 0366d7e9693c930cf18c0f50cc16acec064e96c5

$ docker --version
Docker version 1.12.2, build bb80604

```

**Clear Linux docker versions** 

```
$ docker-containerd --version
containerd version 0.2.0

$ docker-runc  --version
runc version 1.0.0-rc1
spec: 1.0.0-rc1

$ docker --version
Docker version 1.12.1, build 8eab29edd820017901796eb60d4bea28d760f16f

```

**Comment by gorozco1** [comment]
In the meantime the  workaround to make cc work in ubuntu 16.04 is to install the older version of docker engine:


```
sudo apt-get install docker-engine=1.12.1-0~xenial -y
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by jodh-intel** [comment]
This relates to the OCI version. Docker 1.12.2 generates configuration data at OCI version `1.0.0-rc2-dev`, but `cc-oci-runtime` only currently supports `1.0.0-rc1`:

```
$ sudo cc-oci-runtime --version|grep spec
spec version: 1.0.0-rc1
```

```
$ sudo docker-runc --version|grep spec
spec: 1.0.0-rc2-dev
```

If debug is enabled (see https://github.com/01org/cc-oci-runtime#running-under-docker)...

```
udo mkdir /tmp/cor
sudo mkdir -p /etc/cc-oci-runtime/
cat << EOT | sudo tee /etc/cc-oci-runtime/cc-oci-runtime.sh.cfg
--debug
--global-log
/tmp/cor.log
--hypervisor-log-dir
/tmp
EOT
sudo sed -i -e 's!/usr/bin/cc-oci-runtime!/usr/bin/cc-oci-runtime.sh!g' /lib/systemd/system/docker-cor.service
sudo systemctl daemon-reload
sudo systemctl restart docker-cor
```

... you can see this:

```
$ sudo grep version /tmp/cor.log 
2016-10-17T09:00:18.931378Z:7767:cc-oci-runtime:critical:cannot handle config version 1.0.0-rc2-dev (supported version is 1.0.0-rc1)
```

It's unfortunate that a point release of docker has broken compatibility with runtimes in this way.

See #275 for further details.

**Comment by ewa8949** [comment]
Thanks for the quick feedback.  Installing v1.12.1-0 worked for me.

**Comment by dlespiau** [comment]
We've merged a change making the runtime accept "compatible" OCI versions, ie if the major and minor member are 1.0, we continue. It should fix these kind of problems. See PR https://github.com/01org/cc-oci-runtime/pull/518. 

Closing then.
