### ISSUE TITLE
Clear containers memory latency

### ISSUE THREAD

**Issue by mmartinm** [01org/cc-oci-runtime#333]
Measure Clear Containers RAM  latency during different operations

**Comment by mmartinm** [comment]
Types of operations: Copy , Scale, Add, Triad, Average
Benchmarks:  Integer, Floating point

**Comment by grahamwhaley** [comment]
These are going to be interesting numbers :-)  Can I ask, are we looking for something particular or expecting these numbers from inside a Clear Container to be any different from running on bare metal?

My guess is we are not looking for the latency of individual accesses, but more the overall average access time - so we are looking for those accesses that take substantially longer than on bare metal, the outliers?

I'm mostly curious. Also, are we thinking of doing this on a fairly quiescent system (one container), or a busy one (many containers)?

**Comment by mmartinm** [comment]
Hi 
Actually we have 2 scenarios so far

1  Executed two benchmarks of ramspeed  in only one container (docker-cor and Runc) same Host then baremetal, the numbers were not much different

2 we executed  same benchmarks in 2 containers at the same time in the sam host (docker-cor and Runc) the numbers were reduced 

So currently we are evaluating if this is the best way to measure  the memory latency, and the idea is to have several containers (the limit allowed in one hardware ) automatically running these benchmarks to identify every release if we have  memory degradations

If you have any feedback please let us know:

following more details of the benchmarks and result.

---------------------------------------------------------------------------------------------------------------------

Executed the ramspeed benchmark Integer and floating point (operations: Copy, Scale, Add and Triad - More is better)  in bare metal, Docker-cor and RunC:

Host Hardware:

Processor: Intel Core i5-6260U @ 1.80GHz (4 Cores), Motherboard: Intel NUC6i5SYB, Chipset: Intel Skylake, Memory: 16384MB, Disk: 240GB INTEL SSDSCKJW24, Graphics: Intel Iris 540 (950MHz), Audio: Realtek ALC283, Network: Intel Connection I219-V + Intel Wireless 8260



Scenario 1 one at the time   results:

Bare Metal (Host)
Integer 
INTEGER BatchRun   AVERAGE:   19805.95 MB/s
Floating Point:
FL-POINT BatchRun  AVERAGE:   16448.49 MB/s

RunC (#docker run --runtime=runc -ti <image> bash)
Integer:
INTEGER BatchRun   AVERAGE:   20193.98 MB/s
Floating Point:
FL-POINT BatchRun  AVERAGE:   16547.48 MB/s


Docker-cor (Clear Containers) (#docker run -ti <image> bash)
Integer:
INTEGER BatchRun   AVERAGE:   20259.51 MB/s
Floating Point:
FL-POINT BatchRun  AVERAGE:   16534.58 MB/s


Scenario 2 / 2 containers running same benchmark in same host


Docker-cor (Clear Containers) (#docker run -ti  <image> bash)
Integer:
INTEGER BatchRun   AVERAGE:   10533.49 MB/s
Floating Point:
FL-POINT BatchRun  AVERAGE:   9987.46 MB/s

RunC (#docker run --runtime=runc -ti <image> bash)

Integer:
INTEGER BatchRun   AVERAGE: 10019.57 MB/s
Floating Point:
FL-POINT BatchRun  AVERAGE: 10054.67 MB/s

**Comment by mmartinm** [comment]
Hi 
Actually we have 2 scenarios so far

1 Executed two benchmarks of ramspeed in only one container (docker-cor) same Host then baremetal, the numbers were not much different

2 we executed same benchmarks in 2 containers at the same time in the sam host (docker-cor ) the numbers were reduced

So currently we are evaluating if this is the best way to measure the memory latency, and the idea is to have several containers (the limit allowed in one hardware ) automatically running these benchmarks to identify every release if we have memory degradations

If you have any feedback please let us know:

following more details of the benchmarks and result.
---------------------------------------------------------------------------------------

Executed the ramspeed benchmark Integer and floating point (operations: Copy, Scale, Add and Triad - More is better) in bare metal, Docker-cor:

Host Hardware:

Processor: Intel Core i5-6260U @ 1.80GHz (4 Cores), Motherboard: Intel NUC6i5SYB, Chipset: Intel Skylake, Memory: 16384MB, Disk: 240GB INTEL SSDSCKJW24, Graphics: Intel Iris 540 (950MHz), Audio: Realtek ALC283, Network: Intel Connection I219-V + Intel Wireless 8260

Scenario 1 one at the time results:

Bare Metal (Host)
Integer 
INTEGER BatchRun AVERAGE: 19805.95 MB/s
Floating Point:
FL-POINT BatchRun AVERAGE: 16448.49 MB/s

Docker-cor (Clear Containers) (#docker run -ti  bash)
Integer:
INTEGER BatchRun AVERAGE: 20259.51 MB/s
Floating Point:
FL-POINT BatchRun AVERAGE: 16534.58 MB/s

Scenario 2 / 2 containers running same benchmark in same host

Docker-cor (Clear Containers) (#docker run -ti   bash)
Integer:
INTEGER BatchRun AVERAGE: 10533.49 MB/s
Floating Point:
FL-POINT BatchRun AVERAGE: 9987.46 MB/s

**Comment by dlespiau** [comment]
Where are we with that issue?

By latency, do you mean bandwidth? somewhat different things :)

If those numbers of very different would be worth talking with the qemu team to see if they are in the expected range. qemu may also have tunable parameters that would affect memory bandwidth.

**Comment by mmartinm** [comment]
this issue was focused in memory bandwidth, results were sent and is currently running automated in our daily system tracker
