### ISSUE TITLE
add missing docker integration tests to github repo

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#337]
This issue is to remind me that we have some docker integration tests that need to be added to the github repo.

**Comment by dlespiau** [comment]
Could you be more precise about the kind of tests? are we talking about the exec ones that are today in a PR?

**Comment by dlespiau** [comment]
@chavafg do we now have all of them?

**Comment by chavafg** [comment]
still need to add pause and unpause tests, will have them by the end of this week, then I will close this issue.

**Comment by dlespiau** [comment]
We don't support pause and unpause, nor any plan to support them anytime soon. Not sure of the value of having those tests, we can probably skip them for now?

**Comment by grahamwhaley** [comment]
@chavafg are these tests now covered in https://github.com/clearcontainers/tests/tree/master/integration/docker, and hence can we close or re-assign this to 3.x now (/cc @egernst )

**Comment by jcvenegas** [comment]
all integration test are now maaged in its own repo
