### ISSUE TITLE
Add stress tests 

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#343]
Currently we lack of stress testing. 
It would be ideal to generate new tests with some big workloads for our runtime to check how it behaves under stress.

**Comment by GabyCT** [comment]
These tests have been added and they will run for each new release. However, they are affected by the issue #616. Currently, it is only possible to run and delete 70 containers (using a swarm bench) with a loop of 10 repetitions before the DUT gets hanged or without response. After #616 is solved the number of containers will increase.
