### ISSUE TITLE
All proxy functions/receivers need to be documented.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#350]
Related to #348 and original comments added to PR #306.

**Comment by dlespiau** [comment]
does it make sense to you to downgrade this with "all exported functions"? I think that's what goling checks for. I don't think having a header for all function is really necessary, many little functions are self-documenting.

**Comment by dlespiau** [comment]
PR #360 has a compromise: have golint be happy, ie all exposed symbols are documented. This can be abused a bit a main packages, hiding all symbols in those.

A potential way to limit that abuse in the future could be to restrict the main package to have nothing else but the main function and no object implementation. The package view would look like:
  - ./proxy: the proxy package where all objects currently defined in the main package are defined and exposed (Proxy, Vm, Protocol, ....)
  - ./proxy/daemon: the main package with one file with the main function
  - ./poxy/api: like today

**Comment by dlespiau** [comment]
@jodh-intel golint passes and now enforces that every exposed symbol must be documented. I think that's an acceptable trade-off and certainly widely accepted in other go project.

Happy to close this bug?

**Comment by jodh-intel** [comment]
There still seem to be public functions that are not documented (for example `protocol.Serve()`).

**Comment by dlespiau** [comment]
This issue was moved to clearcontainers/proxy#13
