### ISSUE TITLE
Kubernetes bridged networking kills host network.

### ISSUE THREAD

**Issue by keenemaverick** [01org/cc-oci-runtime#354]
I've been trying to get Kubernetes running using ClearLinux w/ ClearContainers as nodes.

Using these instructions:
http://kubernetes.io/docs/getting-started-guides/docker-multinode/#optionsconfiguration

As far as I can tell, it just adds "--mtu=1472 --bip=10.1.5.1/24" to the ExecStart line in /usr/lib/systemd/system/docker.service

If I have --default-runtime=cor, then the second I run ./master.sh, all host networking just stops. It works fine in runc, though.

I didn't see this listed under the networking limitations on the wiki, but I have a feeling it's related...

**Comment by dlespiau** [comment]
Hi,

Sorry for the late answer. We do not support Kubernetes yet and that's related to the networking indeed. Some sort of Kubernetes support in the works, but we don't have a timeline for this just yet.

**Comment by devimc** [comment]
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
