### ISSUE TITLE
(Ubuntu) cc-oci-runtime --version shows "commit: :%H$"

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#358]
when running cc-oci-runtime --version this is the output:

```
$ cc-oci-runtime --version
cc-oci-runtime version: 0.1
spec version: 1.0.0-rc1
commit: :%H$
```

We expect that commit shows the string of the commit id

**Comment by jodh-intel** [comment]
I suspect this relates to how we're generating the OBS images.

@amshinde - would removing `<param name="exclude">.git</param>` from `_service` resolve this?

**Comment by jcvenegas** [comment]
This is fixed in version packaged by @gorozco1
