### ISSUE TITLE
Find a way to propagate error messages from runtime to docker

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#364]
Right now, when the runtime fails to start a container for whatever reason (we weren't able to start qemu, find the kernel or image, ...) the only feedback containerd and docker gives back to the user is "container not started", which isn't very helpful and people needs extra guidance and manual steps to debug the issue.

We should try to find a way to propagate our error messages to containerd, then to docker. This may mean docker/containerd changes.

**Comment by jodh-intel** [comment]
Agreed.

Related: we could also explore the idea of logging direct to syslog for messages `>= G_LOG_LEVEL_WARNING` so that atleast users will see something in the journal (currently we only log to syslog if the logging subsystem itself fails to generate a log entry).

**Comment by jodh-intel** [comment]
Related: #680.

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#128
