### ISSUE TITLE
Add unit tests for cc-shim

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#374]
We need to be able to unit test cc-shim. Current plan is:

 - Have a small "launcher" go program that spawn the shim
 - mock the proxy (a class in that launcher process)
 - Have tests (within the "launcher" process) stimulating the inputs and checking the shim behaviour

**Comment by dlespiau** [comment]
It seems would that would be also the best option to test terminal size changes. sending SIGNWINCH to the shim and test it sends the hyperstart "window size change" message.

Doing it at the integration test level is acutally quite fiddly.

**Comment by amshinde** [comment]
@dlespiau Instead of using a separate launcher program, how about use a "client" from the api package? I had started off with this approach with the proxy serving the fds of this client alone. Do you see any issues with this, I hadnt got far enough with testing the flow.

**Comment by amshinde** [comment]
And how about we move the protocol.go to a separate package so that the mock proxy can use it as well?

**Comment by amshinde** [comment]
Merged in 3.0
