### ISSUE TITLE
Networking is not available inside the Clear Container

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#38]

**Comment by grahamwhaley** [comment]
This is directly related to the #44 PR

**Comment by jodh-intel** [comment]
Basic networking landed in commit edf18d8c03450f6bf19af1dc5a8cfb7ee3688e6f, so this issue can be closed, but see #81 and #82.

**Comment by mcastelino** [comment]
This is fixed now. However there is a systemd error within the container which does not effect functionality but needs to be fixed.
