### ISSUE TITLE
Update coding  for proxy + shim

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#385]
The following need to be updated for `shim/` (C) and  `proxy/` (go):

- https://github.com/01org/cc-oci-runtime/blob/master/DESIGN.rst#code-layout
- https://github.com/01org/cc-oci-runtime/blob/master/DESIGN.rst#17coding-style-and-strategy
- https://github.com/01org/cc-oci-runtime/blob/master/CONTRIBUTING.md

**Comment by dlespiau** [comment]
Given that we want to split out the proxy and shim before 2.1, I think we can skip that bug entirely for this repo. We'll need contributing documents for each new repos, so opened:

- https://github.com/clearcontainers/shim/issues/2
- https://github.com/clearcontainers/proxy/issues/3

**Comment by dlespiau** [comment]
Reopening as we're going to release 2.1 with proxy and shim included, I misunderstood the plan!
