### ISSUE TITLE
Tests for shim + proxy + cc oci runtime interaction

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#386]
Functional tests must be added

**Comment by dlespiau** [comment]
Should they? aren't existing functional/integration tests enough for those? ie.
  - unit test each components
  - functional tests are executing the runtime that will execute shim and talk to proxy
  - docker integration test like before.

Not sure what you had in mind for that one, could you be more explicit?

**Comment by dlespiau** [comment]
Hi Gaby,

I'm removing this task from the next sprint until it's clear what's the work here :)

**Comment by dlespiau** [comment]
Ok, it still seems to me the integration tests we already have cover shim+proxy+runtime. So closing this issue. We may want to open more specific ones (with actually tests we'd need to add).
