### ISSUE TITLE
Proxy needs debug option

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#393]
The proxy needs an option to generate debug output to make debugging system problems easier.

**Comment by dlespiau** [comment]
I was planning to do that in by https://github.com/01org/cc-oci-runtime/issues/345, so closing as duplicate.

**Comment by jodh-intel** [comment]
Ok. I'd make that a P2 as the lack of debug is extremely painful.

**Comment by dlespiau** [comment]
hint taken :)
