### ISSUE TITLE
proxy gives broken pipe error when control-c entered via shim

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#400]
Entering control-c in a `cc-shim`-connected console gives the following `cc-proxy` error:

```
error writing I/O data to hyperstart: write unix @->/var/run/cc-oci-runtime/870cefa4d1dc681a77fc9ebb6145ff1905d446c2138f15781890b5b5f9893976/ga-tty.sock: write: broken pipe (0 bytes written)
```

The interrupt isn't sent to the workload  and the shim environment then becomes unresponsive.

This behaviour is seen using branch https://github.com/01org/cc-oci-runtime/tree/redesign-for-cc-2.1 with or without #382.

**Comment by amshinde** [comment]
@jodh-intel What version of the container image did you use to test this?

**Comment by jodh-intel** [comment]
This was actually using @jcvenegas's `container-target` image (the only one that works currently?), although I think he's working on getting the image in tje `clear-containers-image` package working.

**Comment by amshinde** [comment]
Looked at this briefly today. But I wasnt able to replicate it, instead I see that the proxy forwards the killcontainer message, but is waiting for a response from hyperstart forever.  Will try to see whats happening tomorrow.

**Comment by amshinde** [comment]
@jodh-intel The recent fixes pushed to the 2.1 branch and to the shim in master should have fixed this. Can you confirm?

**Comment by sboeuf** [comment]
@jodh-intel Have you been able to check if you still have the issue you were seeing, now that 2.1 is merged into master ?

**Comment by jodh-intel** [comment]
Yep - confirmed as fixed.
