### ISSUE TITLE
Investigate SemaphoreCI

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#405]
https://semaphoreci.com/ looks like an interesting alternative to Travis:

- supports nested kvm
- permits ssh login to help debug build failures.

**Comment by grahamwhaley** [comment]
Adding xref - this being worked in in #409 I believe

**Comment by jodh-intel** [comment]
I've now reworked the Travis scripts to also work with SemaphoreCI on #409.

**Comment by jodh-intel** [comment]
Although #409 is now merged, keeping this issue open for now to remind us that SemaphoreCI support isn't working fully due to the "freezing" issue that SemaphoreCI are investigating (see comment on #409).

**Comment by grahamwhaley** [comment]
I don't suppose you have a link to the semaphoreCI bug report or similar do you @jodh-intel ? (I suspect not, or I suspect you would have posted it already :-)

**Comment by jodh-intel** [comment]
There isn't one - it's handled via email I'm afraid.

**Comment by jodh-intel** [comment]
It's difficult to say, but it appears the hang/freeze happens "around the time" that `tests/integration/docker/network.bats` runs. The problem is that the hang/freeze isn't instant - it seems to happen a few seconds after one of the test operations runs.
