### ISSUE TITLE
runc as spawner inside the VM

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#407]
We could try to use runc inside the VM to apply the relevant isolation policies.

The goal is to make hyperstart use runc instead of the current built-in isolation mechanisms. runc uses an OCI config file, we could generate one from the hyperstart exec information.

We should be able to configure (either build time or run time) how hyperstart does the isolation:
  - built-in (what exists today)
  - runc (an easy way to do the first runc integration would be to send the OCI file through hyperstart, well, not quite, probably with some things stripped (like network ns)

**Comment by grahamwhaley** [comment]
Just to note,
 it is not clear if we need or require the whole of runc or if we can just have a slim libcontainer wrapper. Nor is it clear how we will pass the isolation and constraint data through to whatever we do end up using. Passing (a potentially filtered) copy of the OCI JSON is one reasonable sounding option, in which case there may be little value in using libcontainer directly, as much of the runc overhead may be the json parsing for instance. Some initial investigation is reaquired.

**Comment by devimc** [comment]
out of scope - Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
