### ISSUE TITLE
Instrument Virtio-blk latency

### ISSUE THREAD

**Issue by dborquez** [01org/cc-oci-runtime#416]
Virtio block device is a paravirtualized device for kvm guest.
The goal is to determine the latency at different layers of the virtualization stack for virtio-blk.

Layers to be analyzed:
1. Guest
2. Host/Guest switching
3. Host/Qemu switching
4. QEMU
5. Host

**Comment by dborquez** [comment]
Analysis done.
Enable this metric for automated tracking in progress.

**Comment by dlespiau** [comment]
@dborquez What's the status of this and the deliverables? does this issue belong to github?

**Comment by dborquez** [comment]
@dlespiau is not an issue.
