### ISSUE TITLE
global log is currently enabled by default

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#42]
This is useful for debug/diagnostics since all runtime operations are logged to `/run/opencontainer/containers/cc-oci-runtime.log`. However, on a busy server that file could grow fast.

We should probably

- Disable the global log by default and document how to configure docker to pass
   "`--global-log /run/opencontainer/containers/cc-oci-runtime.log`" to `containerd`.
   See: [`setup_logging()`](/01org/cc-oci-runtime/blob/master/src/main.c#L245).
- Update `README.rst` on the new behaviour (no global log by default if run stand-alone).

**Comment by jodh-intel** [comment]
Although docker allows the runtime to be passed to the daemon using `dockerd --add-runtime cor=/usr/bin/cc-oci-runtime`, there is no equivalent option to specify options to pass to the runtime.

This leaves us with a couple of options:

- Create an `/etc/docker/daemon.json` file that specifies the runtime and its options as shown in:
  https://github.com/docker/docker/blob/master/docs/reference/commandline/dockerd.md#docker-runtime-execution-options

- Subvert `docker-containerd` so that it is actually a script that does something like:

```
#!/bin/sh

runtime=/usr/bin/cc-oci-runtime
runtime_args="--global-log=/run/opencontainer/containers/cc-oci-runtime.log"

exec /usr/bin/docker-containerd.REAL --runtime "$runtime" --runtime-args "$runtime_args"
exec 
```

Neither of these is particularly palatable since the former breaks stateless-ness and the latter complicates maintenance and is arguably confusing since those options won't appear in the `dockerd` `ps` output.

**Comment by jodh-intel** [comment]
A variant of option 2 is to subvert the runtime itself so that dockerd gets called as something like:

```
dockerd --add-runtime cor=/usr/bin/cc-oci-runtime.sh
```

... and `cc-oci-runtime.sh` is:

```
#!/bin/sh

args="--global-log=/run/opencontainer/containers/cc-oci-runtime.log"

exec /usr/bin/cc-oci-runtime $args $@

**Comment by jodh-intel** [comment]
Note that the global log gets written to atomically so that if it gets deleted or moved, it will just get recreated. This would allow a tool like `logrotate` to deal with it if it becomes too large for some users.

**Comment by jodh-intel** [comment]
Subverting the runtime itself may be the best bet for now particularly since currently debug output is forcibly enabled. The script would allow it to be disabled meaning the logs would shrink hugely - a quick test creating, starting and deleting a CC results in 234 lines in the global log, but with debug disabled only 4 lines get logged.

**Comment by grahamwhaley** [comment]
Out of those options, subverting the runtime with a shell replacement seems the best to me.
I still think we should disable the global log by default, and either put the subvert in place but without the log enabled (as a placeholder), and either way - heavily document how to use the global log (via the subvert), with a strong recommendation for `logrotate` or equivalent.
I don't think we should enable by default and hope nobody leaves it like that and overflows their machine.

**Comment by devimc** [comment]
@jodh-intel what about ```--exec-opt``` ?  this option is used to pass options to runtime, isn't it?

**Comment by jodh-intel** [comment]
It claims to be in some places, but actually doesn't appear to do what we want. It's documented as only allowing specific (cgroup) options to be passed to the runtime but I admittedly haven't checked to ensure the code reflect the docker doc yet.
