### ISSUE TITLE
Add a new command line option in test-campaign.sh to specify LOG_DIR

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#428]
We'd like to be able to control where the logs are going to be output so we can control where test-campaign.sh is going to write its log files.

That's useful to have several scripts adding logs to that directory, test-campaign.sh being one of potentially several scripts doing that.

**Comment by chavafg** [comment]
Opened #567 to address this issue.

**Comment by dlespiau** [comment]
Merged! you can use the Fixes: tag in commit message to automatically close the corresponding issue

```
Fixes: https://github.com/01org/cc-oci-runtime/issues/428
```

https://help.github.com/articles/closing-issues-via-commit-messages/
