### ISSUE TITLE
Handle container exit when run  in standalone mode

### ISSUE THREAD

**Issue by amshinde** [01org/cc-oci-runtime#436]
Our current flow for exiting under docker is,

Container exits within the VM (either clean exit or termination signal sent by the shim)->  shim receives the exit code through proxy ->shim exits with the exit code.
This causes the runtime to be invoked by docker with delete command, and the runtime then  sends a qmp shutdown to the VM. 
This flow does not work when run standalone as shim exits but qemu is not killed.

I am opening this issue to discuss how we need to change the flow. For the standalone mode  to work, the shim will need to shutdown the hypervisor(maybe send "destroypod" to the proxy?)

**Comment by dlespiau** [comment]
Do we know why qemu isn't terminating? sounds like we should always be able to shutdown the VM in delete?

**Comment by amshinde** [comment]
@dlespiau From my testing, we are able to shutdown the VM in delete. But running in standalone mode without docker, delete is not called when the container process exits.

**Comment by dlespiau** [comment]
oh, it would make sense the tests call delete if they call create, delete is supposed to cleanup what create does. I think we were merely relying on systemd's container.target shutting down the VM for us.

**Comment by amshinde** [comment]
Ok. That sounds like the right things to do.

**Comment by jcvenegas** [comment]
So we need to shutdown the vm in two cases:

-start: destroy the vm after the workload exits
-delete: destroy the vm and clean up from create

Probably we would like to kill the vm just in one place, after the inital workload exits. This mean that we could shutdown just before cc-shim exits.

Then the cases hare:
create->start (after start workload ends cc-shim destroy the vm, in both cases docker and standalone)
create->start->delete (if start workload is still working, kill it (and  will kill the vm as well) )

I added destroypod to cc-oci-runtime:
https://github.com/jcvenegas/cc-oci-runtime/tree/topic/kill-vm-using-destroy-pod
destroypod allow us to  shutdown vm,  but if this make sense we will need to add destroy pod support in cc-shim and a way to tell it that is a "start workload" becase "exec workloads" does not need to call destroypod.

**Comment by dlespiau** [comment]
As discussed with Archana, closing this one.
