### ISSUE TITLE
Vendor virtcontainers 0.1.0

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#438]
To protect the runtime against virtcontainers API tweaks, we should vendor virtcontainers 0.1.0. See PR https://github.com/01org/cc-oci-runtime/pull/422#issuecomment-262280175

Note: I used ciao-vendor last time I had to vendor something.

**Comment by sboeuf** [comment]
@dlespiau can you give the link to the example code where you used ciao-vendor ?

**Comment by dlespiau** [comment]
oh, that was to vendor glog, I used:

```
ciao-vendor vendornew github.com/golang/glog 23def4e6c14b4da8ac2ed8007337bc5eb5007998 "Apache 2.0" https://github.com/golang/glog.git
```
