### ISSUE TITLE
QA should add a git tag when a release candidate passes all tests

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#452]
Once all tests for a **release**  have passed, the QA infrastructure needs to add a git tag in ISO-8601 format (`YYYY-MM-DD`) to show that all tests were successful.

Tag format should be:

```
YYYY-MM-DD.qa-passed
```

We might want to use an annotated tag to record details of the environments and tests used. The repo will soon record the "well-known" artifacts (#445), but the ideal is to run the tests twice - once with the well-known versions and once with the latest available artifacts.

**Comment by chavafg** [comment]
@jodh-intel should we define the frequency of the release candidates? Or they should be based on new functionality added?

**Comment by grahamwhaley** [comment]
CC @sameo @dlespiau as well.

**Comment by chavafg** [comment]
@jodh-intel, @grahamwhaley, @sameo, @devimc Is this still relevant for cc-oci-runtime, we are now releasing minor versions when there are important bug fixes.

**Comment by jodh-intel** [comment]
@chavafg - that's a good question. The release process seems to be working well without this, so I'm inclined to say let's close this issue. But let's get a quorum consensus on the idea.

**Comment by grahamwhaley** [comment]
Are those tests any different from the current 'qa-passed' tests? if not, then I think we already have an implicit 'tests passed' from the 'qa-passed' that will be attached to the last PR merge before the release... As @jodh-intel says, it looks like we are already working fine without this, so I'm happy to have this closed.

**Comment by chavafg** [comment]
@grahamwhaley , yes, those are the same tests that are executed on every PR and commit to the repo. 
Closing this issue.
