### ISSUE TITLE
Produce packages for Fedora/Redhat/Centos and Ubuntu using best-practise native facilities

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#453]
We currently produce packages using SuSE's OBS service [1]. This has a couple of limitations though:

- It is currently not possible to download the required repository key using https.

  Only supporting http is not acceptable from a security perspective.

- Too much manual intervention is required to generate the packages "automatically".

  The per-distro package generation is automated, but there is still a need for human intervention to update the required input files (`*.dsc` for example).

Rather than relying on OBS, we could use the best-practise facilities for the main distributions, namely:

- Create a launchpad.net ppa for Ubuntu:
  https://help.launchpad.net/Packaging/PPA

- Create packages using copr for Fedora/Redhat/Centos:
  https://fedorahosted.org/copr/

---
[1] - https://build.opensuse.org/project/show/home:clearlinux:preview:clear-containers-2.0

**Comment by egernst** [comment]
I agree with this.   Having said that,   can we close this but consider opening a new item for 3.0?  At the very least, open against the packaging repo?
