### ISSUE TITLE
Update the qemu-lite OBS package with "--enable-vhost-net"

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#467]
We need --enable-vhost-net to work with 2.1 and be in sync with the clear package

**Comment by sameo** [comment]
To be clear, the OBS spec:

https://build.opensuse.org/package/view_file/home:clearlinux:preview:clear-containers-2.0/qemu-lite/qemu-lite.spec?expand=1

does not enable vhost-net, it seems.

**Comment by amshinde** [comment]
Updated the qemu-lite package in OBS to enable vhost-net:

https://build.opensuse.org/package/view_file/home:clearlinux:preview:clear-containers-2.0/qemu-lite/_service:set_version:qemu-lite.spec?expand=1
and 
https://build.opensuse.org/package/view_file/home:clearlinux:preview:clear-containers-2.0/qemu-lite/debian.rules?expand=1

**Comment by dlespiau** [comment]
Thanks! closing then.
