### ISSUE TITLE
9p fs cannot handle unlinked files

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#47]
When trying to update a debian docker container, I got some errors which seem to be related to 9pfs. 
root@ede543359f58:/etc/apt# apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease                               
Get:2 http://httpredir.debian.org jessie-updates InRelease [142 kB]            
**E: Unable to determine file size for fd 11 - fstat (2: No such file or directory)**

Looking at google, found that this qemu issue is related: 
https://bugs.launchpad.net/qemu/+bug/1336794

**Comment by gorozco1** [comment]
Yes this is an issue related to the bug in launchpad, I think this is an issue that also can be follow on the linux kernel mailing list.. .

**Comment by grahamwhaley** [comment]
So we need to decide if this is 'our bug', or a qemu bug, that is probably already being handled. I think we discussed some already - let's try to make a decision and document/label here appropriately.

**Comment by gorozco1** [comment]
I think we need to raise the priority on this bug... maybe @anthonyzxu might now something

**Comment by devimc** [comment]
fixed kernel and qemu-lite side
