### ISSUE TITLE
Use non-installed shim and proxy for functional tests

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#475]
cc-shim and proxy socket used by cc-oci-runtime are hardcoded with a path defined at build time. This works fine if cc-shim is installed or and proxy is using that path, but running functional test must use last built shim and proxy.

**Comment by devimc** [comment]
@jcvenegas  @dlespiau  
I think some extra options should be added to cor and proxy
--shim-path and --proxy-socket-path for cor
--socker-path for cc-proxy

**Comment by jcvenegas** [comment]
@devimc  that sounds good a way to modify these paths +1

**Comment by jodh-intel** [comment]
@devimc - +1 to this idea!

**Comment by chavafg** [comment]
I think this issue is already resolved, right? With #431

**Comment by dlespiau** [comment]
Yes, closing.
