### ISSUE TITLE
"port" is not implemented

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#48]
Currently is not possible to map a specific port to a container.
It should be possible to do something like this 
docker-upstream port test 8080

**Comment by grahamwhaley** [comment]
I'll note that this is probably tied to the networking issue #38 and thus also the networking branch.

**Comment by mcastelino** [comment]
Should be fixed by https://github.com/01org/cc-oci-runtime/pull/76

**Comment by GabyCT** [comment]
This was verified using release 9920.
 # docker run -tid -p 8080:80 --name test ubuntu bash
33ef2395ddc9596b652ad267f87f9d40fa157913b52a2a3ccae8f4b253580f25
 # docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                  NAMES
33ef2395ddc9        ubuntu              "bash"              5 seconds ago       Up 5 seconds        0.0.0.0:8080->80/tcp   test
 # docker port test
80/tcp -> 0.0.0.0:8080
