### ISSUE TITLE
2.1 qemu doesn't exit from time to time

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#497]
I can still see some "hangs" running the docker run. The failure case is:

- everything looks good, process inside the VM exits, shim exits, proxy has all the right traces
- delete does send the destroypod
- the qemu process is still around after delete and "docker run" waits for it to exit

**Comment by dlespiau** [comment]
My guess is destroypod doesn't actually shutdown the VM in some cases, could be fixed by https://github.com/dlespiau/hyperstart/commit/9eb01be141d000a910acc1fa604ddec9e59247f1

**Comment by dborquez** [comment]
Logs for a failed run that corresponds to this issue:
- cc-oci-runtime.log: http://pastebin.intel.com/view/5b71ebca#L2
- ps aux: http://pastebin.intel.com/view/c15fd7c7#L4
- Journalctl docker-cor: http://pastebin.intel.com/view/24a7f421

**Comment by dlespiau** [comment]
So to fix this bug we need:

  - To package the 2 topmost commit of https://github.com/dlespiau/hyperstart/tree/20161201-intel (@jcvenegas could you take care if this?)
  - Merge https://github.com/containers/virtcontainers/pull/70 and re-vendor the package

**Comment by amshinde** [comment]
@dlespiau Nice!

**Comment by dborquez** [comment]
- 5k repetitions that starts and stops 10 containers passed
- free memory at the begining: 16000 MB
- free memory at the end: 330MB
- Issue that persist:
- qemu-lite-system-x86_64 instances non released (orphaned) at the end of the test: 202
- Next test: 64K repetitions

**Comment by dlespiau** [comment]
The 2.1 branch now has the fixes for that one. We also need the VM image version >= 12020 (I have also a PR (https://github.com/01org/cc-oci-runtime/pull/515) in flight to update the recommended VM image version, but it's not strictly needed to test that fix).
