### ISSUE TITLE
cc-proxy/cc-shim high availability

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#505]
If cc-proxy crashes:

1. all cc-shim instances terminate.
2. cc-proxy will not be able to restore its internal state after restarting.

We need to work on:

1. Have cc-shim retry connecting to the proxy when the socket is closing/disappearing
2. Have cc-proxy re-build all its states when restarting, based on the stored information

**Comment by laijs** [comment]
the virtio-serial is not package based transport, it seams hard to find the message header when cc-proxy re-connect to hyperstart.

**Comment by sameo** [comment]
This issue was moved to clearcontainers/proxy#4
