### ISSUE TITLE
Do not start the pause container

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#511]
Because of hyperstart killing its pod when the last container within it dies, we have to start the pause container to keep the pod alive.

We need to either:

1. Modify hyperstart so that it optionally keep its pod always alive
2. Handle hyperstart events so that we can restart the pod from cc-oci-runtime.

**Comment by jcvenegas** [comment]
@sameo can we close this one ?

**Comment by sameo** [comment]
Tracked here:  https://github.com/containers/virtcontainers/issues/225
