### ISSUE TITLE
Add a -daemonize option to cc-proxy

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#520]
It would nice to be able to daemonize the proxy from the command line. The key here would to fork to the daemon process once the proxy is able to handle connections on its socket.

  -  maybe use https://github.com/sevlyar/go-daemon
  - "daemonize" once the socket has been created
  - original process exits, daemon process continues and will accept socket connections

The runtime could use this feature to auto-start the proxy when needed.

**Comment by sameo** [comment]
This issue was moved to clearcontainers/proxy#5
