### ISSUE TITLE
Docker tests (that involve tty) fail after running functional tests on redesign-for-cc-2.1

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#527]
We have some tests that are failing randomly on the redesign-for-cc-2.1 branch and we do not have the root cause yet. 

```
not ok 4 stdout forwarded using exec
# (in test file exec.bats, line 55)
#   `$DOCKER_EXE exec -ti containertest ls /etc/resolv.conf 2>/dev/null | grep "/etc/resolv.conf"' failed
# 0d41931b116e135b0a32cfc361b68e25fdfa1a0cf8d8153f77c492581116a338
```

also from #523:
```
not ok 3 Exit Code from container process when running under a terminal
# (in test file exit-code.bats, line 52)
#   `[ "${status}" -eq "${exit_status}" ]' failed
# 7e89e7c6b16d
# 
# 0
Dubious, test returned 1 (wstat 256, 0x100)

not ok 3 Check that pseudo tty is setup properly when allocating a tty
# (in test file terminal.bats, line 27)
#   `echo "${output}" | grep "$tty_dev"' failed
# d1c92879937d

```

**Comment by jodh-intel** [comment]
All the `.bats` tests should be calling `cleanup_common()` (in `tests/functional/common.bash.in`) in their `teardown()` to get more complete failure details. `cleanup_common()` isn't "docker-aware", but crucially checks `$BATS_ERROR_STATUS` and dumps out the value of `$output` (via the standard bats `lines` array) plus shows the debug logs.

**Comment by devimc** [comment]
seems like the problem is that functional tests are running before docker tests
probably shim is breaking the tty

**Comment by chavafg** [comment]
I inverted the order of the tests, first running docker and then standalone functional tests and now everything is working, so yes, maybe the functional tests are breaking the terminal.

**Comment by jcvenegas** [comment]
@devimc @chavafg so lets close #529

**Comment by jodh-intel** [comment]
It would be good to understand exactly how it's breaking the tty, but meantime we could run the tests using `script --return -c 'make functional-tests' && script --return -c 'make docker-tests'` or similar so they both get a new tty (pty) device to work with.

**Comment by jcvenegas** [comment]
@jodh-intel  agree to know why, @chavafg  shall we change the issue tittle to something like "docker tests fail randomly on redesign-for-cc-2.1 after run functional-test"

**Comment by chavafg** [comment]
@jcvenegas yeap, changing the bug tittle.

**Comment by devimc** [comment]
@chavafg  re-test it please
I can't reproduce it

**Comment by GabyCT** [comment]
@devimc I will re-test this pr
