### ISSUE TITLE
Create 2.1 OBS packages

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#530]
It would be nice to generate OBS packages for both the clear-containers-2.0 and the master branches.

**Comment by dlespiau** [comment]
I think we should create another OBS project for 2.1 called clear-containers-2.1, like we have clear-containers-2.0 today.

That clear-containers-2.1 project will have packages from the 2.1 branch (master until we have, eventually, a 2.1 branch). That was we can maintain a set  of package for each major architecture version.

  - http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-2.0/
  - http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-2.1/

**Comment by gorozco1** [comment]
repos for testing for cc-oci-runtime 2.1 is ready

http://download.opensuse.org/repositories/home:/patux:/clear-containers-2.1/Fedora_24/
http://download.opensuse.org/repositories/home:/patux:/clear-containers-2.1/xUbuntu_16.04/

**Comment by gorozco1** [comment]
Repos updated and released: 

http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-2.0
http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-2.1
