### ISSUE TITLE
Update wiki now 2.1 is in master

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#532]
Review/refresh the wiki pages, in particular the installation instructions and:

- https://github.com/01org/cc-oci-runtime/wiki/Installation
- https://github.com/01org/cc-oci-runtime/wiki/Limitations

**Comment by amshinde** [comment]
Updated Limitations page  to remove exec from the list.

**Comment by sameo** [comment]
Updated the Fedora installation page.

**Comment by gorozco1** [comment]
Updated Ubuntu installation page

**Comment by jodh-intel** [comment]
This has been done on various PRs.

- Install instructions have been refreshed:
  https://github.com/01org/cc-oci-runtime/wiki/Installation
  (install docs now live in-tree here: https://github.com/01org/cc-oci-runtime/tree/master/documentation)

- Limitations wiki page has become: https://github.com/01org/cc-oci-runtime/wiki/Limitations-2.1.0
