### ISSUE TITLE
Exit codes from non-interactive runs are not handled.

### ISSUE THREAD

**Issue by amshinde** [01org/cc-oci-runtime#54]
With runc:

```
$ sudo docker-upstream run --runtime runc  debian /usr/bin/perl -e 'exit 55'
$ echo $?
55
```

with cc-oci-runtime:

```
$ sudo docker-upstream run  debian  /usr/bin/perl -e 'exit 55'
$ echo $?
0
```

**Comment by dlespiau** [comment]
So, after a first look at this, I think the best approach is to wait until the exec over qmp/qagent is done (issue #18) and refactor the run functionality using the same mechanism. Putting back to ready until then. Do shout if you don't agree.

**Comment by dlespiau** [comment]
If we want that feature before #18 it should be easy enough (famous last words) to write a small temporary patch that solves the issue:

- Create a Virt I/O serial device bound to a unix socket for the guest to communicate the exit value back to the host. Open that socket and put in the set of fds to listen to.
- modify the generated .container exec to echo $? > /dev/virtio-ports/$name_of_the_device after the command executed (mechanism used by the 'run' command)
- make sure we read back the exit value when qemu exits and use it for the runtime own exit value.

**Comment by chavafg** [comment]
I am adding some tests for this in PR #523 
But when running under a terminal, the return code is not handled correctly.

Without -t 
```
cc-tester@clear-cc-ci ~ $ sudo docker run -i ubuntu /usr/bin/perl -e 'exit 55'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
cc-tester@clear-cc-ci ~ $ echo $?
55
```


With -t 
```         
cc-tester@clear-cc-ci ~ $ sudo docker run -ti ubuntu /usr/bin/perl -e 'exit 55'
cc-tester@clear-cc-ci ~ $ echo $?
0
```

**Comment by chavafg** [comment]
Actually, the tests are passing, there is an issue with running functional stand-alone tests first (Issue #527) and then running this test.

**Comment by devimc** [comment]
seems like this bus was fixed
@chavafg  @GabyCT  can I close it ?

**Comment by GabyCT** [comment]
@devimc it has been fixed, you can close it

**Comment by dlespiau** [comment]
@GabyCT Don't hesitate to close the issue yourself if you confirm/think it can be closed.
