### ISSUE TITLE
Exec (2.1) is not working on Ubuntu 16.04 with docker 1.12.5

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#543]
Running the exec tests in Ubuntu 16.04 with docker 1.12.5 show failures
bats exec.bats
 ✗ modifying a container with exec
   (in test file exec.bats, line 38)
     `docker exec -d containertest bash -c "echo 'hello world' > file"' failed
   68949065a422e059f87ef01738f9590f74d60333fb39d4558aa923ae96070a1b
   68949065a422        ubuntu              "bash -c 'sleep 50'"   1 second ago        Up Less than a second                       containertest
   Error response from daemon: rpc error: code = 2 desc = containerd: container not started

**Comment by jcvenegas** [comment]
This should be fixed by #545

**Comment by jcvenegas** [comment]
@GabyCT could you confirm is working properly now?

**Comment by GabyCT** [comment]
This is working now with the fix of #545 
# bats exec.bats  
✓ modifying a container with exec
 ✓ exec a container with privileges
 ✓ stdout forwarded using exec
 ✓ check exit code using exec

# docker run --name containertest -d ubuntu bash -c "sleep 50"
f00e7f0554ba46410c9cc88a9c4bd566d29e1d585219037a99c3557efe09156c
# docker exec -d containertest bash -c "echo 'hello world' > file"
# docker exec containertest bash -c "cat /file"
hello world
