### ISSUE TITLE
Exec (2.1) is not working with docker 1.13 in Fedora 24

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#544]
Exec tests are failing
bats exec.bats
 ✗ modifying a container with exec
   (in test file exec.bats, line 38)
     `docker exec -d containertest bash -c "echo 'hello world' > file"' failed
   68949065a422e059f87ef01738f9590f74d60333fb39d4558aa923ae96070a1b
   68949065a422        ubuntu              "bash -c 'sleep 50'"   1 second ago        Up Less than a second                       containertest
   Error response from daemon: rpc error: code = 2 desc = containerd: container not started
✗ exec a container with privileges
   (in test file exec.bats, line 45)
     `docker exec -i --privileged containertest1 bash -c "mount -t tmpfs none /mnt"' failed with status 126
   7c4afddd04598f049c69ed60081bd9371854e9b7a6d5184e761a26852c51747d
   rpc error: code = 2 desc = containerd: container not started
✗ check exit code using exec
   (in test file exec.bats, line 73)
     `[ "$status" -eq 42 ]' failed
   0546365a8c73127b23c7b210447bd96db559a699d080a67eb48dc17dcd0d1d26

**Comment by jcvenegas** [comment]
this is probably related with #543

**Comment by jcvenegas** [comment]
This should be fixed by #545, @chuyd  could you please that exec is working now ?

**Comment by gorozco1** [comment]
well, the doc of clear-containers 2.0 says we should lock to use docker-engine-1.12.1-0.2.rc2.fc24.x86_64 in fedora... this might probabbly changed and we need to update wiki with the latest compatible docker.

**Comment by GabyCT** [comment]
@jcvenegas the main reason of why it is not working is related with #548

**Comment by gorozco1** [comment]
@GabyCT does it work ok with docker-engine-1.12.1-0.2.rc2.fc24.x86_64 ?

**Comment by GabyCT** [comment]
@gorozco1 yes it worked with 1.12.1

**Comment by gorozco1** [comment]
@GabyCT thanks for the update. 

We need to make sure cc2.1 is compatible with newer dockers
