### ISSUE TITLE
Networking: No default gateway  provided in network branch

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#55]
The network branch does not provide docker bridge IP address as default gateway. With lack of a correct gateway, the container cannot communicate with external IPs.

Steps:

1. Start docker daemon using cc-oci-runtime
```
#dockerd-upstream --add-runtime cor=/usr/bin/cc-oci-runtime --default-runtime=cor
```
2. Start a container 
```
#docker-upstream run -ti debian sh
```
3. Verify default gateway is the same as Host docker bridge (currently is not the same)
```
#ip route
```
The expected output:
```
#ip route
default via $DOCKER_BRIDGE_IP dev eth0 
...
```
4. Try to ping to a reachable ip e.g. your host IP 
```
#ping $HOST_IP
```
    This will fail:
```
#ping $HOST_IP   
PING $HOST_IP ($HOST_IP): 56 data bytes
ping: sending packet: Network is unreachable
```

The current workaround is set the the default gateway manually, inside the container run:
```
#ip route add default via $DOCKER_IP_BRIDGE
#ip route
default via $DOCKER_IP_BRIDGE dev eth0 
$DOCKER_IP_BRIDGE/16 dev eth0  proto kernel  scope link  src ...
```

**Comment by jcvenegas** [comment]
To reproduce this steps use PR: #44

**Comment by mcastelino** [comment]
Should be fixed by https://github.com/01org/cc-oci-runtime/pull/76

**Comment by chavafg** [comment]
Verified and it is working now, closing this issue. 

root@containers-skylake /etc/systemd/system # docker run -ti debian bash
[    0.073158] systemd[1]: Failed to initialise default hostname
root@e744ca84bc7e:/# ip route
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2 
root@e744ca84bc7e:/# ping 10.219.106.29
PING 10.219.106.29 (10.219.106.29): 56 data bytes
64 bytes from 10.219.106.29: icmp_seq=0 ttl=58 time=0.715 ms
64 bytes from 10.219.106.29: icmp_seq=1 ttl=58 time=0.532 ms
64 bytes from 10.219.106.29: icmp_seq=2 ttl=58 time=0.989 ms
