### ISSUE TITLE
Packages for Ubuntu 16.10 are not available

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#569]
Currently there is a bug buildling the linux-container kernel, same building qemu-lite and cc-oci-runtime.

This affects both 2.0 and 2.1 builds

**Comment by grahamwhaley** [comment]
If you get a chance, some details of which packages and what the build errors look like might be nice to record.

**Comment by gorozco1** [comment]
This the error that linux-kernel build trows:

https://hastebin.com/isilejafon.sql


The error building qemu-lite is: 

Nothing provides libpng12-0, nothing provides libpng12-dev


The error building cc-oci-runtime: 
Missing dependencies: qemu-lite, linux-container-kernel  

Checking on fixing the qemu-lite with dependencies change... The problem with the kernel still ongoing...

**Comment by amshinde** [comment]
@gorozco1 Ubuntu16.10 does not have libpng12-0 and libpng12-dev :
http://packages.ubuntu.com/search?keywords=libpng&searchon=names&suite=yakkety&section=all

How about you change the above dependencies to just "libpng-dev" in the qemu-lite.dsc and debian.control files for the qemu-lite package. I think that should fix it.

**Comment by gorozco1** [comment]
@amshinde thanks for the suggestion, I'll do that and check if that does not break the other builds.

**Comment by amshinde** [comment]
Also for the kernel build, try applying this patch for Ubuntu distros:
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.8-rc2/0002-UBUNTU-SAUCE-no-up-disable-pie-when-gcc-has-it-enabl.patch

**Comment by gorozco1** [comment]
wow! thanks for the quick help and update on this I will try :)

**Comment by grahamwhaley** [comment]
Nice work @gorozco1 and @amshinde :-)
Just to note @gorozco1 , I would be wary of using paste sites such as hastebin.com etc. here, as their pastes are not permanent (expiring after anywhere between 1 and 30 days typically), so we will lose the details here in this ticket...

**Comment by jodh-intel** [comment]
I'm a little confused here - we shouldn't need png libs to build `qemu-lite` as we explicitly disable the gui in `debian.rules`.

**Comment by grahamwhaley** [comment]
I've a feeling the need for png libs is something currently inherently tied into QEMU, and there is no way to trivially/easily disable it in the build/config right now. I think we've discussed this with @anthonyzxu a couple of times before. Of course, we'd love to not have png requirements in QEMU, but we have also agreed that at the moment the space taken by the un-used png libs is shared across all QEMU instances (Clear Container instances), so the final overhead is actually minimal.

**Comment by jodh-intel** [comment]
I think that was `libpixman` which shouldn't be required, but seems entangled in the qemu build; `libpng` isn't required for `qemu-lite` on clr for example.

**Comment by grahamwhaley** [comment]
Ah, thanks @jodh-intel - mea culpa!

**Comment by amshinde** [comment]
@jodh-intel You are right,  png was disabled in the configure options, but the build requirement wasnt changed.
@gorozco1 Can we take get rid of the png libraries ?

**Comment by gorozco1** [comment]
@grahamwhaley note taken the log for the kernel-build are here now for reference:
https://gist.github.com/gorozco1/937f9b1302cd64e25bc87cad09e99375


At the same time I tried to build qemu-lite the changes @amshinde suggested to only point to libpng-dev instead of libpng12

Error log here: (complains about no libpng12-0and libpng12-dev) 
https://gist.github.com/gorozco1/3459cbd5b80fbc14940382c7d8e3b7f3


I am going to try to remove the dependencies to libpng at all as we do in clearlinux

**Comment by gorozco1** [comment]
@jodh-intel @amshinde @grahamwhaley qemu-lite built without libpng in f24,25, u1604,u1610

**Comment by gorozco1** [comment]
patch for kernel suggested by @amshinde fixed the issue, linux-container kernel builds on Ubuntu 16.10.

cc 2.0 and 2.1 released and available for Ubuntu 16.10
