### ISSUE TITLE
tag 2.0.0 builds cc-proxy and cc-shim.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#591]
`cc-proxy` and `cc-shim` were added to the repo before the `2.0.0` tag was applied.

As such, building at this tag currently means that both these extra applications are built, even though they are not used. This is awkward for users since they must have all the go dependencies installed to have a successful build even though the resulting proxy and shim binaries are not used.

We need to disable building `cc-proxy and `cc-shim` for CC 2.0.

**Comment by grahamwhaley** [comment]
Was fixed by #603 - but the 'Fixes' comment was not in the commit or merge, so didn't get auto-closed (I think).
