### ISSUE TITLE
Feature request: Provide error messages about missing KVM support on command line if cor runtime crashes back to prompt

### ISSUE THREAD

**Issue by eadamsintel** [01org/cc-oci-runtime#596]
Recently I did a bios upgrade and it turned off my virtualization without my knowledge.  When I tried to run a clear container (--runtime=cor) it just crashed back to the prompt and the error logs using journalctl -u docker.service did not help me realize this.  It would be helpful if I got some kind of indication that kvm was not enabled or working.   In general if any common error messages especially those related to the VM are passed back to the command prompt it would have helped me in this case.

**Comment by jodh-intel** [comment]
Hi @eadamsintel - this is a fair point and touches on the following issues:

- #341 
- #364
