### ISSUE TITLE
Travis: Build cc-oci-runtime within travis environment 

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#61]
We need to figure out how to build cc-oci-runtime within travis environment.

**Comment by grahamwhaley** [comment]
With merge #65 is this now fixed? If not, can we give a status update here for the record?

**Comment by jodh-intel** [comment]
The basic build is now working (see https://travis-ci.org/01org/cc-oci-runtime/builds/149692903), but we're still not running `make check`. However, that could be handled on another issue as this one is purely to build the runtime under Travis.

**Comment by grahamwhaley** [comment]
#69 added for 'make check in Travis' request. Closing this item as done.
