### ISSUE TITLE
Docker is leaking file descriptors

### ISSUE THREAD

**Issue by dborquez** [01org/cc-oci-runtime#616]
It seems as though docker-containerd and docker-containerd-shim are leaking file descriptors.
I ran a 4K repetition loop that starts and stops 10 concurrent containers, and docker failed to continue launching more containers at iteration 3276.

**Steps to reproduce the issue:**

1. To reproduce this issue, I ran the following script to a reasonable number of iterations i.e. 4000

```
REPS=4000
MAX_CONTAINERS=10

docker_run()
{
  local ITER=$1
  echo -e "\nIteration $ITER"
  for i in $(seq 1 $MAX_CONTAINERS); do
        docker run -d clearlinux
        bash -c "while true; do sleep 1; done"
  done
}

docker_stop()
{
        docker stop $(docker ps -qa)
        docker rm -f $(docker ps -qa)
}

run_test()
{
for j in $(seq 1 $REPS); do
        docker_run $j
        sleep 2
        docker ps -a
        docker_stop
done
}
run_test
```

2. Count how many file descriptors are open in each iteration for the processes: qemu-lite-system-x86_64, dockerd, dockerd-containerd and docker-containerd-shim:

`lsof -n -p $(echo $(pidof  "${PID}") | awk '{$1=$1}1' OFS=" -p ") | wc -l"`

3. The count of file descriptors increased with the number of iterations as is shown in the following charts:

![docker-containerd](https://cloud.githubusercontent.com/assets/13384596/22226518/623c5510-e18c-11e6-965e-b76250984a53.png)
![docker-containerd-shim](https://cloud.githubusercontent.com/assets/13384596/22226578/94689742-e18c-11e6-8e2f-31ccca2757c7.png)

4. Docker hangs after iteration 3275 once the number of docker-containerd opened files was: 65535
```
# lsof -n -p $(pidof docker-containerd) | wc -l
655535

```
5. max open files for docker-containerd process
```
cat /proc/$(pidof docker-containerd)/limits | grep "Max open files"
Max open files            65536
```

The complete data collection with count of file descriptors for the processes listed in 3 is below:

[output_23012017_0036_csv.txt](https://github.com/01org/cc-oci-runtime/files/725252/output_23012017_0036_csv.txt)

6. docker info:
```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: cor runc
Default Runtime: cor
Security Options:
Kernel Version: 4.9.5-294.native
Operating System: Clear Linux Software for Intel Architecture
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63 GiB
Name: clrContainersDev
ID: 3FHD:CE6K:AEUC:WLZS:RSSE:MEZU:2LSP:GODG:BSCC:XMA6:Q4SB:SSAN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 52
 System Time: 2017-01-23T17:32:04.880737686Z
 EventsListeners: 0
```

**Comment by dborquez** [comment]
Repeat this experiment with runC shows a constant number of opened files by docker-containerd and docker-containerd-shim as shown in the chart below:

![count_opened_files_runc-docker-containerd](https://cloud.githubusercontent.com/assets/13384596/22259023/5f08db82-e229-11e6-9ea2-5c27535905b5.png)
![count_opened_files_runc-docker-containerd-shim](https://cloud.githubusercontent.com/assets/13384596/22259024/5f162828-e229-11e6-92cb-60725bd9b1c3.png)

- Inspecting fds left opened by cc-shim and cc-proxy.

**Comment by sameo** [comment]
@dborquez Could you please check if you see this leak with the latest HEAD (571b53bdb1254165b7036a828d01c8cf88eed726) ?

**Comment by dborquez** [comment]
@sameo for sure.

**Comment by devimc** [comment]
related to cgroups, working on that ...

**Comment by GabyCT** [comment]
This behavior was observed in stress testing as after a time of running and deleting containers the test device just did not respond. Even a while of running and deleting containers, you need to reboot the test device or it will not come back.

**Comment by dborquez** [comment]
A test that starts and stops 10 concurrent containers for 10K times has passed Ok.
The FD leaks has not impeded the test execution.
