### ISSUE TITLE
Error encountered while running postgres container

### ISSUE THREAD

**Issue by amshinde** [01org/cc-oci-runtime#64]
Started a postgres container :
sudo docker-upstream run -it  postgres

Works with runc. Get the message
```
LOG:  database system is ready to accept connections
```
When run with cc-oci-runtime, it shows the following:
```
Success. You can now start the database server using:
    pg_ctl -D /var/lib/postgresql/data -l logfile start
cat: -: No such file or directory
```
Above message is not very helpful. Need to root cause the issue.

**Comment by devimc** [comment]
could be related to #47 (open-unlink-fstat) ?

**Comment by grahamwhaley** [comment]
Any suggestions how we might verify that, or track it down? Are there some specific logs and things we should be looking for for example?
I would suggest trying it with a different type of filesystem mount and seeing if that helps/changes - which might give us clues, but would not imho be conclusive (or a fix ;-).

**Comment by jodh-intel** [comment]
@amshinde - can you include a few more lines of context for the runc scenario? Presumably with runc you also get that `Success. You can now start the database server using` message?

Some info on 9p debugging...

- From the hypervisor side: [tracing quick start](01org/qemu-lite/blob/master/docs/tracing.txt#L8)

- From the kernel side: Modify `/lib/systemd/system/opt-rootfs.mount` to add "`,debug=0x04`" to "`Options=`". See https://www.kernel.org/doc/Documentation/filesystems/9p.txt.

**Comment by devimc** [comment]
related to #47 
fixed kernel and qemu-lite side
