### ISSUE TITLE
Set up port mapping rules inside the VM.

### ISSUE THREAD

**Issue by amshinde** [01org/cc-oci-runtime#644]
Docker sets up port mapping rules inside the container ns (so we need to propagate them into the VM). Part of the fix for issue #578

**Comment by sameo** [comment]
@amshinde Can we try restoring all iptables rules into the VM and deleting the VM netns one instead of just supporting port mappings ?

**Comment by sameo** [comment]
cc @mcastelino

**Comment by amshinde** [comment]
Merged.
