### ISSUE TITLE
containerd error in docker logs: ERRO[69610] failed to close stdin: rpc error: code = 2 desc = containerd: process not found for container 

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#646]
There's something we don't do "correctly" still when spawning the shim. To reproduce:

- I'm using docker 1.12.5 (can probably be reproduced elsewhere)
- running the full docker integration test suite shows quite a few of those in the docker logs

edit: oh, actually I was running docker 1.12.5 for this one.

**Comment by devimc** [comment]
checking 1.12.1 ...

**Comment by devimc** [comment]
Cannot reproduce using docker 1.12.1
@dlespiau  can we close it?

**Comment by chavafg** [comment]
Haven't hit this error again, I think we can close it.

**Comment by devimc** [comment]
closing issue

thanks @chavafg
