### ISSUE TITLE
Fail a test if a container, cc-shim or qemu is left behind

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#647]
We need to tighten a bit our tests by failing if something unexpected happens to better understand where the bugs are. It's not enough to say "at the end of the test run, we have processes left behind".

Tests need to ensure:

- setup(): no qemu(-lite) process is running on the system
- setup(): no cc-shim is running on the system
- setup(): there's no running container on the system

- teardown(): no qemu(-lite) process is running on the system
- teardown(): no cc-shim is running on the system
- teardown(): there's no running container on the system

at teardown(), if we detect a problem, we fail the test. That way we'll know which test failed. We should then try to clean up the environment for the next test (kill container, qemu, cc-shim).

**Comment by jodh-intel** [comment]
Agreed, although we can tighten up the checks further:

* "`function()`: no `$thing` is running on the system *as the user running the tests*".
