### ISSUE TITLE
Implement cloud-init to provide complex network configurations to clear-containers

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#68]
In order to support more than one interface or bridges, routing etc we need a mechanism in clear-containers image that can handle such complex configuration. It can also add extra features to customize the container with specific values or even to setup proxies.

**Comment by mcastelino** [comment]
Pre-req to support to https://github.com/01org/cc-oci-runtime/issues/94

**Comment by mcastelino** [comment]
@gorozco1 

Please see requirement called out in https://github.com/01org/cc-oci-runtime/issues/95
This will help you understand the exact subset of requirements for supporting swarm

**Comment by grahamwhaley** [comment]
Hi @gorozco1 @mcastelino did we implement enough init support when doing the Swarm work to close this ticket down, or do we still intend/need to do more work (and will that be cloud-init etc.).
 thanks.

**Comment by dlespiau** [comment]
This issue doesn't seem very specific and is probably included in the 2.1 work items already (propagate config to the VM, multiple interfaces, ...).

Ok to close?

**Comment by mcastelino** [comment]
@dlespiau Yes. This was the initial direction. Any implementation that supports complex network configuration propagation from host to guest and configuration within the guest is fine.

**Comment by dlespiau** [comment]
perfect, superseding that issue for the other ones we have opened, now that we've looked into networking and have a better idea of what we need to do.
