### ISSUE TITLE
improve debug behaviour

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#680]
Since docker does not allow options to be passed to the hypervisor, enabling runtime debugging is awkward [1].

Rather than having to reconfigure docker to use the `cc-oci-runtime.sh` helper utility to enable debug, we could control debug via environment variables. Something like:

```
$ docker run --env='["COR_DEBUG" : "enabled", "COR_DEBUG_DIR": "/tmp" ]' -ti busybox ...
```

The best approach might be to only have one environment variable, pointing to a configuration file:

```
$ docker run --e COR_CONFIG_FILE=/etc/cc-oci-runtime/cc-oci-runtime.cfg -ti busybox ...
```

We could even drop the variable and just have the runtime check a list of well-known directories, looking for a `cc-oci-runtime.cfg` configuration file.
 
----
[1] - documented at https://github.com/01org/cc-oci-runtime/wiki/Debugging.

**Comment by jcvenegas** [comment]
This issue was moved to clearcontainers/runtime#125
