### ISSUE TITLE
Docker-engine 1.12.1-1.fc25 no longer available from docker repository: Fedora instructions now incorrect

### ISSUE THREAD

**Issue by keenemaverick** [01org/cc-oci-runtime#687]
Testing out the Fedora install instructions, it fails on the step to install docker-engine-1.12.1-1.fc25.

When using dnf --showduplicates to find available versions, these are the only ones listed:

[keene@localhost ~]$ sudo dnf --showduplicates list docker-engine
Last metadata expiration check: 0:16:06 ago on Tue Feb 21 11:17:37 2017.
Available Packages
docker-engine.src                     1.13.0-1.fc25                  docker-main
docker-engine.x86_64                  1.13.0-1.fc25                  docker-main
docker-engine.src                     1.13.1-1.fc25                  docker-main
docker-engine.x86_64                  1.13.1-1.fc25                  docker-main

Since 1.12.1-1 is not listed, the installation as documented can no longer be completed.

**Comment by devimc** [comment]
Hi @keenemaverick thanks for reporting this issue
Unfortunately Clear Container 2.1 has compatibility issues with docker 13.x (swarm)
If you do not need swarm you can use that version
we are still working on documentation to describe limitations

**Comment by dlespiau** [comment]
Ok, let's also ask docker about those, it'd be nice if they can provide the 1.12 rpms on Fedora 25: https://github.com/docker/docker/issues/31256

**Comment by dlespiau** [comment]
Another possible way would be to install the binary package: https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz

**Comment by egernst** [comment]
For the in-tree .md file, I instead installed the fc24 version.  ie, s/25/24:

$ sudo dnf config-manager \
  --add-repo \
  https://docs.docker.com/engine/installation/linux/repo_files/fedora/docker.repo
$ sudo dnf install docker-engine-1.12.1-1.fc24

**Comment by egernst** [comment]
I included the fix in  #682.  This pull request adds installation directions in-tree;  once this is merged the now erroneous wiki-page should be removed, and the new .md should be referenced.

**Comment by eadamsintel** [comment]
I checked out the instructions in #682 referenced above and had issues trying to install the package after this step

# dnf config-manager --add-repo https://yum.dockerproject.org/repo/main/fedora/24

This is the error I got. The instructions should cover how to install the private key.

warning: /var/cache/dnf/yum.dockerproject.org_repo_main_fedora_24-49ad15a9cfbbed21/packages/docker-engine-1.12.1-1.fc24.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Public key for docker-engine-1.12.1-1.fc24.x86_64.rpm is not installed

**Comment by egernst** [comment]
Thanks Eric. I'll update this later tonight. Can you suggest an edit in the meantime?  I expect this should resolve the issue (after adding the repo).

$ sudo dnf makecache fast

Thanks,
Eric

On Feb 27, 2017, at 4:41 PM, eadamsintel <notifications@github.com<mailto:notifications@github.com>> wrote:


I checked out the instructions in #682<https://github.com/01org/cc-oci-runtime/pull/682> referenced above and had issues trying to install the package after this step

dnf config-manager --add-repo https://yum.dockerproject.org/repo/main/fedora/24

This is the error I got. The instructions should cover how to install the private key.

warning: /var/cache/dnf/yum.dockerproject.org_repo_main_fedora_24-49ad15a9cfbbed21/packages/docker-engine-1.12.1-1.fc24.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Public key for docker-engine-1.12.1-1.fc24.x86_64.rpm is not installed

**Comment by eadamsintel** [comment]
I found that I had to edit /etc/yum.repos.d/yum.dockerproject.org_repo_main_fedora_24.repo and add in the following to the end. Can you update your instructions for that?

gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg

**Comment by dlespiau** [comment]
The documentation has been merged with the instructions above and the wiki is pointing at them (not totally an optimal ToC, but it'll have to do for now). Please do re-open if another problem arises.
