### ISSUE TITLE
Updates to support OCI spec version v1.0.0-rc5

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#690]
Review what, if anything, needs to be updated to support spec version `v1.0.0-rc4`.

See:
- https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc4
- https://github.com/opencontainers/runtime-spec/compare/v1.0.0-rc3...v1.0.0-rc4

**Comment by devimc** [comment]
last release https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5

**Comment by jodh-intel** [comment]
Related: #691,  #746, #747.
