### ISSUE TITLE
Documentation Updates for clearlinux.org

### ISSUE THREAD

**Issue by amyleeland** [01org/cc-oci-runtime#70]

**Comment by grahamwhaley** [comment]
We have a number of documents that need updating or writing. Including at least:

* clearlinux.org
  * https://clearlinux.org/features/clear-containers
    Needs updating to reflect our move to QEMU from kvmtool. Update wrt to rkt and Docker.
  * https://clearlinux.org/documentation/gs-clear-containers-getting-started.html
    Pertains to CC1.0. We need to update for CC2.0 - probably initially by creating a separate CC2.0 page and linking to it from the above, whilst noting the above is deprecated.
   * We need to publish the CC architecture document on clearlinux.org

* github docs
  * The INSTALL_DOCKER.rst file needs a refresh as Docker have released 1.12 now, and we have made improvements to CC
  * We can add interim documents detailing how to hand install on Fedora and Ubuntu whilst we work out the details of the deb and rpm packaging and publishing.

* blogs
  * We should blog our CC2.0 updates

**Comment by gorozco1** [comment]
we need to update this link as well:

https://clearlinux.org/documentation/bundles_overview.html

**Comment by grahamwhaley** [comment]
OK, I believe all the listed updates here are now done. If there are new/other/more doc updates that need doing then we should open new issues for them.
I am closing this issue.
