### ISSUE TITLE
Apply JSON features for CI

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#701]
Setup for results (Json)

**Comment by grahamwhaley** [comment]
Hi @GabyCT - can you make these issues a bit more verbose please, just in case somebody else needs to pick them up and implement them? :-)  I know you probably understand exactly what they mean, but I at least could do with some more details :-)

**Comment by GabyCT** [comment]
@grahamwhaley thanks for the feedback, this issue will be closed as I will assign myself this issue #435
