### ISSUE TITLE
linux-container version is wrong on ubuntu installation 

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#702]
After following the installation document for Ubuntu 16.10, the linux-container package says to be version `4.9.4-53`, but when running `uname -r` on a clear container, it does not match with the installed one.

```
fuentess@ubuntu-cc-test:~$ ls /usr/share/clear-containers/vmlinux.container -l
lrwxrwxrwx 1 root root 26 Jan 20 17:43 /usr/share/clear-containers/vmlinux.container -> vmlinux-4.9.4-53.container

fuentess@ubuntu-cc-test:~$ sudo docker run -ti ubuntu uname -r
4.9.4-49.testing
```

**Comment by jcvenegas** [comment]
I think is fixed now ? @gorozco1  any update on this ?

**Comment by gorozco1** [comment]
This is fixed in latest buidlds can you verify @chavafg

**Comment by chavafg** [comment]
Verified, this is fixed :), closing this issue.
