### ISSUE TITLE
Capture hypervisor stdout+stderr to log

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#71]
The runtime should arrange for the hypervisor standard output and standard error to be captured to files to aid in debugging. Something like:

```
/run/opencontainer/containers/${container}/hypervisor.stdout
/run/opencontainer/containers/${container}/hypervisor.stderr
```

**Comment by devimc** [comment]
@jodh-intel  I think that redirecting hypervisor stdout+stderr to /run/opencontainer/containers/${container}/hypervisor.stdout is not a good idea, because when a container fails its state directory is deleted and therefore hypervisor's logs are deleted too

**Comment by jodh-intel** [comment]
Yes, in the docker scenario, you're right. In which case we should atleast ensure the stdout+stderr is sent to the log. Assuming global logging is enabled, that will ensure the error is ateast viewable after docker has deleted the container.

(We might want to convert actual "\n"'s into the literal chars '\\' and 'n' (like syslog and journald do) to ensure that the global log shows multi-line qemu output on a single line).

**Comment by devimc** [comment]
@jodh-intel 
I'd like to create these files when global logging is enabled
/run/opencontainer/containers/$container-hypervisor.stdout
/run/opencontainer/containers/$container-hypervisor.stderr
using this approach log files won't be deleted by docker when COR fails
what do you think?

**Comment by jodh-intel** [comment]
Maybe a slight variation would be better: if we added a `--hypervisor-log-dir` option users could decide where the logs should be created, rather than using the "dirname" of the `--global-log` path.

That does mean to get full output you'd need to specify 3 options (`--debug --global-log ... --hypervisor-log-dir ...`) but now we have `cc-oci-runtime.sh` (#99), that shouldn't be too onerous for users.

Please ensure you update `README.rst` so it's clear to users how to use the feature.
