### ISSUE TITLE
Create test for volume creation and mount

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#73]
related to #23

**Comment by grahamwhaley** [comment]
@chavafg - can we have a bit more detail here please?

**Comment by chavafg** [comment]
Need to add tests to verify that adding a volume to a container works using cc-oci-runtime.

**Comment by chavafg** [comment]
Created PR https://github.com/01org/cc-oci-runtime/pull/259 to solve this issue.
