### ISSUE TITLE
Document the API and requirements of the 'mini-OS'

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#731]
The kernel and small rootfs that run in the VM to launch the workload (what is known sometimes as the 'mini-OS') has certain requirements and needs - such as supporting a hyperstart protocol on a known serial port etc., and also some base kernel config expectations (9pfs etc.).  We should document these.

**Comment by grahamwhaley** [comment]
Just noting this is mildly related to #251 and @jcvenegas

**Comment by jcvenegas** [comment]
@grahamwhaley  I will add the mini-os reference documentation to https://github.com/clearcontainers/osbuilder  the things I have in mind:

- packages needed
- image partition layout
- describe boot sequence ( services, targets )

**Comment by egernst** [comment]
This is located in other repo -- closing this one
