### ISSUE TITLE
Performance test of CC with qemu-2.7-lite 2.1.1+git.d7de93a

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#734]
A performance improvement in qemu-lite has ben pushed.
https://github.com/01org/qemu-lite/commit/741f430a960b5b67745670e8270db91aeb083c5f

We need to test and verify the metrics of CC with qemu-2.1.1+git.d7de93a

**Comment by chavafg** [comment]
Tests were executed and no performance degradation was found in compare to old qemu.

**Comment by dlespiau** [comment]
@gorozco1 Just to be sure, this means our packaged qemu-lite is now including this improvement?

**Comment by gorozco1** [comment]
@dlespiau yes, this means this new qemu-lite with patch to improve heap size has been tested, measured and released.
