### ISSUE TITLE
Rework the installation instructions to have numbered steps

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#739]
From @rcaballeromx (PR https://github.com/01org/cc-oci-runtime/issues/739):

> Please make sure that the steps are easy to follow, even and especially, if you have never done them before. The steps should be numbered if they need to be performed in a specific order. Optional or alternative steps should be added as notices. The way this content is written, the steps are headings which is not correct. The best practice is to have a step for every independent action. Simple actions, such as creating a directory and moving inside, may not require their own step.

**Comment by dlespiau** [comment]
@GabyCT I've assigned this to you, hopefully you have some time to look into this across all the different installation instructions.

1. We need to merge PR https://github.com/01org/cc-oci-runtime/issues/739 and PR https://github.com/01org/cc-oci-runtime/pull/733,
2. Then rework the steps as recommended by @rcaballeromx. Don't hesitate to contact him if things are unclear.

**Comment by GabyCT** [comment]
@dlespiau and @sboeuf I already talked with @rcaballeromx and I will work in the installation instructions with the steps, notes, etc

**Comment by dlespiau** [comment]
@GabyCT Excellent, thanks Gaby. PR #739 and PR #733 are now merged so I'd suggest starting with this one before #741 as it should be a quick-ish one.

I'm also linking how a few projects do install instructions for inspiration:

https://docs.docker.com/engine/getstarted/step_one/
https://kubernetes.io/docs/getting-started-guides/kubeadm/
https://ceph.com/install/

**Comment by GabyCT** [comment]
closing this issue as the PR is already merged
