### ISSUE TITLE
Networking: Use netlink socket to discover and setup networking

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#74]
In the first implementation direct invocation of the iproute2 utilities has been used to discover and setup networking configuration by spawning iproute2 commands. This is inefficient and not very secure.

Replace the commands with a pure netlink based implementation which will allow for more efficient setup.

**Comment by dlespiau** [comment]
Now that we use libmnl, can we close this?

**Comment by gorozco1** [comment]
true, we should close this

**Comment by mcastelino** [comment]
implemented by PR https://github.com/01org/cc-oci-runtime/pull/173
