### ISSUE TITLE
Reduce the number of steps and manual instructions in the REHL installation document

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#741]
I've counted 71 commands in the current REHL installation instructions. That's too many.

I suggest we create scripts to automate those so we can end up with a handful of steps max. The logical steps are as below:

 - Step 1: compile gcc, it's needed for qemu-lite. A script that compiles the gcc dependencies as well as gcc. Add a note that this is an optional step if one can use the Red Hat Developer Toolset. DST6 has gcc 6.2.x already.
 - Step 2: Install golang
 - Step 3: compile qemu-lite. A script that compiles qemu-lite.
 - Step 4: Install container kernel and rootfs. A script that installs both.
 - Step 5: Install clear containers (included glib/json-glib)
 - ... same as today

Each script should have:
  - An option to install the whole thing in a non-default location (/usr/local today): `--prefix /opt/clearcontainer`.
  - An option for verbose output.
  - Keep the logs of the build somewhere in under the prefix in case things go wrong.
  - Be idempotent. Successive invocations should work and continue an aborted installation. That means keeping track of which sub-steps have been done and start at the next step when invoked again.
  - Share code with the .ci/ci-setup.sh
  - In the non verbose case, the script should display the big things it's doing:
```
...
Installing glib 2.46.2
Installing json-glib 1.2.2
...
```

Now, it'd be possible to squash the 3-5 together. For that we'd have a master script invoking the other ones.

I'm sure I'm forgetting things, don't hesitate to suggest things and/or edit this post as needed.

**Comment by GabyCT** [comment]
@dlespiau and @sboeuf I will work on this, one question in which directory should I place the script?

**Comment by sboeuf** [comment]
Maybe create this in a script/ or setup/ directory.

**Comment by sameo** [comment]
We should just point the installation instructions at something similar than:
https://github.com/clearcontainers/dockerfiles/blob/master/2.1/build/centos/README.md

**Comment by dlespiau** [comment]
@sameo yes!

**Comment by GabyCT** [comment]
Closing this issue as the script was already merged
