### ISSUE TITLE
Can only launch 7 cor containers under ciao-down

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#757]
Under ciao-down (https://github.com/01org/ciao/tree/master/testutil/ciao-down), I can only launch 7 `cor` based containers, and then the 8th one errors on launch. You can see the error at the end of the attached run.log.txt file. I'm using the following script to launch:

```
#!/bin/bash
set -e
count=1
while true
do
	echo Number : $count
	time -p docker run -d busybox /bin/tail -f /dev/null
	count=$(($count+1))
done
```

I will note this launches containers in quick succession - but even once the script has failed I cannot launch any new ones - same error.

I've had a look at the system limits, in case it was related to `TasksMax` or similar, but I can't find anything. I have lots of disk and RAM free. It always fails at the 8th launch.

I've enabled `cor` and `proxy` logging, and attached the files.

I had a read of the logs, and there are a couple of things to note, but I don't know if they are relevant:
- In proxy.log.txt, line 967: there seems to be an odd 'log line overlap' between 'Hardware Clock' and 'ipaddress' - that could just be a journalctl problem though?
- previously (but not in this log?) I saw errors where the proxy/hyperstart appeared to fail to open 'ga-ctl.sock' with 'unavailable'
- In run.log.txt we will see there are 8 container launch attempts, with the last 3 being:
    - d887
    - df93
    - d42c (the one that fails)

yet in the proxy log we see no output for `df93`. To note, a `docker ps` shows the container to be running. Possibly this is another journalctl issue, but maybe it is a clue?

This problem is easily reproducible for me with `ciao-down` at commit afdd394 or possibly 6a64829, under F24. My `ciao-down` VM was allocated 2 CPUs and 3G of RAM
[proxy.log.txt](https://github.com/01org/cc-oci-runtime/files/851049/proxy.log.txt)
[run.log.txt](https://github.com/01org/cc-oci-runtime/files/851050/run.log.txt)

At this point with ciao-down I have installed:
 - Docker v1.12.1
 - cc-oci-runtime 2.1.1 commit d7de93a13edc9eddf7d6417f20a6faa3f56136dc
 - Ubuntu 16.04.2 LTS

If you need me to run more experiments or capture more data or logs then just ask away...

**Comment by grahamwhaley** [comment]
Ah, also adding the cc-oci-runtime.log - which is the file that actually shows the 'ga-ctl.sock' and similar errors.

[cc-oci-runtime.log.txt](https://github.com/01org/cc-oci-runtime/files/851131/cc-oci-runtime.log.txt)

**Comment by jodh-intel** [comment]
I've run through https://github.com/01org/cc-oci-runtime/blob/master/documentation/Quickstart-Clear-Containers-in-a-Ubuntu-VM.md and I can run 50 `cc-oci-runtime` containers before I get an error from `docker`:
```
docker: Error response from daemon: shim error: open pid: no such file or directory.
james@singlevm:~$ docker ps|wc -l
50
```

My Fedora 25 host system has 32G RAM, with 8G allocated to qemu.

**Comment by grahamwhaley** [comment]
Thanks @jodh-intel . I just tried this with 4G of RAM, and managed to run 15 containers.
That gives me some clues. Upon failure, if I check `free`, we have just less than 2G on the host. If I then adjust hypervisor.args to allocate 1G to the qemu VM and try again I can launch 28 containers (in 4G), and the failure happens when `free` reaches just under 1G. So, I believe this may well be the problem @jcvenegas noted/saw a few weeks back where QEMU will not launch if the host `free` memory is less than that requested to be allocated to the VM.
Now, how do we check/verify that is the problem? I didn't see any obvious errors in any of the logs to point me at that. Any thoughts @jcvenegas ?

**Comment by jodh-intel** [comment]
Any update on this?

**Comment by grahamwhaley** [comment]
Good nudge. Actually, yes - let me dig up the details. Basically the kernel restricts VM overcommit by default. Disabling that lets you create containers until you run out of available memory (which may or may not be what you want...).
 The command to disable the overcommit restriction is:

```# sysctl -w vm.overcommit_memory=1```

It would be good if:
 - somehow the error messages in the logs were more informative about why the container could not be launched - but that may come down to interaction with `QEMU`.
 - we could document the settings of vm.overcommit_memory more precisely

Thus, for now we may want to keep this item open until we get time to investigate/implement those.
