### ISSUE TITLE
Setup network providing MAC address instead of predicting interface name

### ISSUE THREAD

**Issue by sboeuf** [01org/cc-oci-runtime#758]
Now that https://github.com/clearcontainers/hyperstart/pull/11 has been merged to our hyperstart version, we can, in a more reliable way, select the network interface we want to setup inside the VM.
Indeed, instead of trying to predict the network interface name created by the hypervisor, we only have to provide to hyperstart the same MAC address we provided to the hypervisor when defining TAP interface.

**Comment by dlespiau** [comment]
This seems merged.
