### ISSUE TITLE
Update hyperstart package to include MAC address support

### ISSUE THREAD

**Issue by sboeuf** [01org/cc-oci-runtime#759]
Now that we have merged https://github.com/clearcontainers/hyperstart/pull/11, we want to rely on latest hyperstart version in CC 2.1, so that we can use the MAC address as a parameter to setup the network inside the VM. It is will be now up to the caller to decide if he wants to provide the interface name or the MAC address related to this interface. Because it can be not reliable to try to predict a network interface name, this solves this issue by accepting the same MAC address that has been passed through the hypervisor command line.
We have to update hyperstart package and image version in cc-oci-runtime.

**Comment by jcvenegas** [comment]
The package was update it should be ready in next clear-containers image version (14130)

**Comment by sboeuf** [comment]
Thanks @jcvenegas !

**Comment by dlespiau** [comment]
I think all of this is now merged.
