### ISSUE TITLE
docs: Fix legacy markup poor practices

### ISSUE THREAD

**Issue by rcaballeromx** [01org/cc-oci-runtime#763]
In the past, documents were authored without the guidance of best practices or a style guide. As evidenced in #752 #730 and others. Both the MarkDown and ReST markup usage need to be corrected. I can provide all the information about best practices and a simple style guide for us to follow. However, I cannot fix all the documents alone.

**Comment by jodh-intel** [comment]
Hi @rcaballeromx - #788 can be used to handle the style guide.

Can this issue now be closed? Our process I think now is two-pronged and should handle all eventualities:

- The doc team are now required to approve all doc-affecting PRs
- The doc team can independently raise PRs to address issues with existing documentation.

**Comment by rcaballeromx** [comment]
@jodh-intel This issue is about cleaning up the existing content. The steps you describe will help us avoid making this issue larger but they sadly do not fix it. I am working on getting additional resources to perform this task. Please do not close this issue.
