### ISSUE TITLE
Workload should be PID 1 of its namespace inside the VM

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#768]
Currently hyperstart in PID 1 inside the workload namespace. That shouldn't be the case:

```
$ docker run -it busybox sh
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/hyperstart
    3 root       0:00 sh
    4 root       0:00 ps
```

**Comment by dlespiau** [comment]
re-opening. I think that was closed by github automatically with the Fixes tag, but we want to close this when the hyperstart with the fix is in an image we use.

**Comment by grahamwhaley** [comment]
@egernst @sboeuf Should we transition this to 3.x now? And, has/did the hyperstart fix land and/or will it be fixed with the new agent?

**Comment by sboeuf** [comment]
@grahamwhaley we don't have the fix for hyperstart, but the new agent does not have this issue :)

**Comment by grahamwhaley** [comment]
OK, and the new agent is for CC3.x only, right - so, we can close this.... yes?

**Comment by sboeuf** [comment]
Yes, and yes.
