### ISSUE TITLE
vm.json defaults don't align with installed cc defaults

### ISSUE THREAD

**Issue by egernst** [01org/cc-oci-runtime#769]
When I install clear containers via a repo such as [1], the dependent images end up going into /usr/share/clear-containers/ and the vm.json at /usr/share/defaults/cc-oci-runtime point to this accordingly.

Now, after convincing myself that I love clear containers so much that I want to move on and build it from source and run it, I go ahead to a make install and notice that the default updates to vm.json point to a non-existent location, /var/lib/cc-oci-runtime/...

I don't see any rationale one why we'd want to change the default location, especially if it is putting an immediate burden on folks who are trying to build and run as fast as possible.  We should update the default to use the same location, /usr/share/defaults/cc-oci-runtime/

[1] http://download.opensuse.org/repositories/home:clearlinux:preview:clear-containers-2.1/Fedora\_25/home:clearlinux:preview:clear-containers-2.1.repo

**Comment by dlespiau** [comment]
Juste a note that, actually, /usr/share/defaults/ isn't a thing outside of clear linux and if we had to package the runtime for other distros, they'd probably make us change that.

Your point still holds thought.

**Comment by jodh-intel** [comment]
Clear Linux overrides the default locations as shown here: https://github.com/clearlinux-pkgs/cc-oci-runtime/blob/master/configure

It's debatable whether these files should live below `/var/lib/` or `/usr/share/`. The Linux FHS would seem to permit both: the latter is "more correct", although the former would allow for a read-only `/usr/`.

**Comment by egernst** [comment]
Just following up because this got me again.  

While it may not be a bug, per se, I think this should be handled in a way that's a bit more kind to users/developers.   How're developers expected to handle this?  Since what the make install updates into vm.json is incorrect (on some distros, at the very least), can we instead of overwriting the installed vm.jsons's path, copy and reuse it?

Ie, make the "make install" a bit smarter in determining what path the vmlinux.container and clear-containers.img is?

**Comment by dlespiau** [comment]
It's still somewhat of a bug I think. We need to decide where those files belong and be consistent across the board.

**Comment by egernst** [comment]
I think it is a bug.  I'm going to open a second issue as well which would solve this.  Basically that we should be able to provide a build option that will build all of the dependent packages.  cc-oci-runtime is just a single binary.  For Clear Containers, we need to also provide mechanism to build from source all of the other components (namely things like container.img and vmlinux/z).   We need to be able to build all the artifacts that are necessary for Clear Containers without necessitating having a login to koji, imo.
