### ISSUE TITLE
package cc-oci-runtime clearlinux aka (bundles)

### ISSUE THREAD

**Issue by gorozco1** [01org/cc-oci-runtime#77]
Clear Linux has a bundles concept: https://clearlinux.org/documentation/bundles_overview.html

We need to package cc-oci-runtime among other components to be easily usable and installabe.

- qemu-lite 
- cc-oci-runtime

**Comment by grahamwhaley** [comment]
Hi. @gorozco1 , unclear if you meant to add and remove the labels or not. I'll re-add them and place this item into the milestone.

**Comment by gorozco1** [comment]
released on image 9890
