### ISSUE TITLE
tests/lib/test-common.bash not generated for metrics tests

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#777]
Presently the tests/metrics tests do not have a Makefile rule to run them, and running them using their top level script `run_docker_metrics` results in the errors:

```workload_time/docker_workload_time.sh: line 31: <path>/cc-oci-runtime/tests/metrics/workload_time/../../lib/test-common.bash: No such file or directory```

The `lib/tests-common.bash.in` file requires pre-processing before it can be used - and `Makefile.am` needs modifying to add a rule for `metrics-tests` or similar, with a tie-in for lib/tests-common.bash via the GENERATED_FILES etc.

We may also want to add a check into `run_docker_metrics` so it aborts if the processed `lib\test-common.bash` file does not exist (that is, abort if somebody is trying to run the test by hand in an unbuilt tree for instance)

**Comment by jodh-intel** [comment]
Hi @chavafg - any update on this?

**Comment by grahamwhaley** [comment]
For reference, a workaround is to do a:
```# make check```
before running the metrics tests, as that will pre-generate the required files.
I or @MarioCarrilloA may get to look at this soon if @chavafg does not.

**Comment by chavafg** [comment]
Hi, taking a look this week.

**Comment by chavafg** [comment]
PR #804  opened to fix this.

**Comment by chavafg** [comment]
This is now merged, so closing this issue.
