### ISSUE TITLE
inconsistencies in packaging of vmlinuz

### ISSUE THREAD

**Issue by egernst** [01org/cc-oci-runtime#816]
Ubuntu has vmlinuz included, whereas Fedora and Clear Linux packages do not.

For OVS-DPDK usage, or any vhost-user based connections, we need to make use of vmlinuz/bzImage.

We should make sure at the very least we are consistent on what we package between distros.

**Comment by jodh-intel** [comment]
It would be helpful for these kinds of issues if we could resolve #672.

**Comment by grahamwhaley** [comment]
Hi @egernst - fmi, could you clarify a little why we need to make use of vmlinuz/bzImage for vhost-user cases - what is the key technical difference here?

**Comment by egernst** [comment]
@grahamwhaley -- Several issues were identified with our existing clear
    container setup and OVS-DPDK.
    -EFI BIOS does not suppot nvdimm
    -pc-lite has multiple bugs and leaks vhost-user memory (appears
    that KVM does not release it).
    -pc-lite does not shutdown with vhost-user.
    
    Because of this, moving to use pc platform and legacy BIOS.

**Comment by grahamwhaley** [comment]
Thanks. To clarify (fmi) - only the QEMU pc-lite model can load kernel ELF images (a Clear Containers optimisation), and currently for OVS-DPDK we need to use a different QEMU pc model both for some extra features and to avoid some issues. Thus, we need a non-ELF kernel image to use with that non-pc-lite QEMU. Thanks @egernst

**Comment by gorozco1** [comment]
vmlinuz/bzImage is now included in cc-oci-runtime >=2.3... Progress has been made on #672 to get the automation tooling to create obs packages automatically.

**Comment by jcvenegas** [comment]
@gorozco1  can we close this one ?

**Comment by gorozco1** [comment]
@jcvenegas  yes, we can close this one.. it is fixed in cc-oci-runtime >=2.1.3
