### ISSUE TITLE
Networking: "docker run --net=container ..." does not work.

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#82]
Known limitation of code used to fix #38.

**Comment by mcastelino** [comment]
@jodh-intel @sameo  In cc-oci-runtime we may not be able to support --net=container. The plan is to support the use case of --net=container which is Kubernetes/appc PODs at this point in time.  Will update this issue with details on the POD implementation. Also add an issue to support Kubernetes/appc PODs.

**Comment by dlespiau** [comment]
Documented the current limitation. We definitely want to be able to support the POD concept, "joining" the VM network would mean executing the container inside an already existing VM. With the current direction we're heading for, it seems that we could implement --net=container.

**Comment by devimc** [comment]
this is a limitation that was documented https://github.com/01org/cc-oci-runtime/wiki/Limitations
Will be fixed in 3.0 - https://github.com/clearcontainers/runtime
