### ISSUE TITLE
cc-shim: cc-shim is not namespaced

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#836]
cc-shim is not namespaced to match the process that it represents. This results in inconsistencies when trying to use the PID reported by docker to examine the process.

```
PID=$(docker inspect --format {{.State.Pid}} <container name|id>)
sudo nsenter --target $PID --mount --uts --ipc --net --pid

```
Will result in incorrect information.

We should place the cc shim in the proper namespaces. Additionally we should document this limitation until we fix this issue.

**Comment by devimc** [comment]
cc-shim is part of the memory cgroup but yes we have to add it to a namespace
adding this limitation to release notes
thanks

**Comment by dlespiau** [comment]
question: is it time to put these bugs/feature request as 3.0 items?

**Comment by devimc** [comment]
@dlespiau I think so, what do you think @mcastelino ?

**Comment by sameo** [comment]
This issue was moved to clearcontainers/runtime#122

**Comment by sameo** [comment]
This issue was moved to clearcontainers/shim#17
