### ISSUE TITLE
CPU % consumption for network

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#838]
Measure cpu % consumption when iperf is running

**Comment by grahamwhaley** [comment]
Hi @GabyCT If there is anything specific we are looking for or expecting to see, or we have plans on what we compare against etc., can you please add them to the ticket (and future tickets) - it helps everybody else understand where we are heading, and will help if somebody else has to pick the issue up for whatever reason.

thanks.

**Comment by GabyCT** [comment]
@grahamwhaley sure, in this case we will measure the cpu % consumption when we have a server and a client (running iperf - bandwidth measurement) using ps.

**Comment by GabyCT** [comment]
@grahamwhaley with the help of ps we will obtain the cpu % of the processes of qemu while running a network measurement

**Comment by GabyCT** [comment]
closing this issue as the PR is already merged
