### ISSUE TITLE
Networking: systemd error ("Failed to initialise default hostname") shown when starting a container

### ISSUE THREAD

**Issue by chavafg** [01org/cc-oci-runtime#84]
The next message appears when running a clear container: 

root@containers-broadwell ~/containers-metrics/test # docker-upstream run -ti ubuntu bash               
**[    0.054929] systemd[1]: Failed to initialise default hostname**
root@975cd940fe3c:/#

**Comment by gfortaine** [comment]
Same error here

**Comment by jodh-intel** [comment]
A fix for this issue has been added to Clear Linux (but it's not yet in an official build).

**Comment by dlespiau** [comment]
Verified it was fixed in the newest image, https://github.com/01org/cc-oci-runtime/issues/146 tracks adding the test to ensure we don't regress.
