### ISSUE TITLE
Improve Release Process using task lists

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#847]
# Idea

If we were to convert https://github.com/01org/cc-oci-runtime/wiki/Release-Process into a task list...

- [ ] Do release task 1.
- [ ] Do release task 2.
    `:`
    `:`
- [ ] Do release task *n*.

... our pre-Release Process would be improved.

# Proposed pre-Release process

The steps taken before we started working through the release process could then become:

1. Raise an issue to handle tracking the new release.
1. Copy the source of https://github.com/01org/cc-oci-runtime/wiki/Release-Process into that issue.
1. Work through the release process issue, ticking the boxes as all the actions are completed.
1. Raise a PR for the release, referencing the issue number for tracking the release.

# Advantages

Tasks lists mean we are much less likely to forget any steps since:
- The person handling the release will have the checklist to guide them.
- The PR reviewers can:
  - Require the `Fixes #XXX` on the release PR.
  - Provide a safety-check to ensure all steps are "checked".

- Finally, we will have improved traceability for each release.

# Disadvantages

- A little more work to produce a release. Hardly onerous though I'd argue.

# Evidence and Rationale

PR #845 is an example that lends weight to introducing such a light-weight process as described above. Missing a step is easily done, so we should do what we can to introduce a lightweight process to help minimise that in the future.

# Follow-up work

If we get agreement on this, we need to document it more fully on the wiki page.

What do we think folks? :smile:

- [ ] @sameo 
- [x] @grahamwhaley 
- [x] @dlespiau 
- [x] @devimc

**Comment by grahamwhaley** [comment]
I'm.... definitely not against it :-)  Personally, if it were me I'd find the ticklist useful - without it I'd probably physically print out a copy and tick things off with a pencil otherwise :-)
I think we had some feedback previously that 'a list or ticklist is the same thing' - but, I disagree - I like the idea of being able to 'tick' things off.
I felt slightly wary of the 'create an Issue step' - but, having that Issue makes a very convenient place to copy the ticklist into - much better than copy/creating a new page per release.
So, I give an
lgtm
but will value what @devimc says, as he is currently handling the releases.

**Comment by devimc** [comment]
lgtm

**Comment by devimc** [comment]
I've just updated the [Release Process page](https://github.com/01org/cc-oci-runtime/wiki/Release-Process)

**Comment by jodh-intel** [comment]
This lgtm - courtesy of @devimc we now have a neat https://github.com/01org/cc-oci-runtime/wiki/Release-Checklist page that we can copy/paste into an issue.

@sameo, @dlespiau - any comments on this? Feel free to tick the appropriate box above :smile:

**Comment by dlespiau** [comment]
Sounds OK to me. I do want to note though that's instead of a check list, the ideal would be to encode that checklist into a script to run.

**Comment by jodh-intel** [comment]
@dlespiau - +1 for automation in the future. I've raised #851 to capture that.

**Comment by jodh-intel** [comment]
Related: #451.

**Comment by jodh-intel** [comment]
We've now been using this process since 2.1.6 (see #863, #881, #899, #922, #940) so closing this issue.
