### ISSUE TITLE
Add dockerfiles for the gabyct/network docker network image

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#848]
Add dockerfile for the image that is using the network metrics

**Comment by jodh-intel** [comment]
Related to #843.

**Comment by jodh-intel** [comment]
The  custom `gabyct/network` docker image is used by:

- `tests/metrics/network/network-metrics.sh`
- `tests/metrics/network/network-metrics-iperf3.sh`

And soon to also be used by:

- `tests/metrics/network/network-metrics-cpu-consumption.sh.in` (#843).

**Comment by jodh-intel** [comment]
Hi @GabyCT - any update on this?

**Comment by GabyCT** [comment]
@jodh-intel, I need some time to do this...kind of busy these days

**Comment by GabyCT** [comment]
@jodh-intel PR #895

**Comment by GabyCT** [comment]
Closing this issue as PR is already merged
