### ISSUE TITLE
md file hotlinks are not rendering correctly

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#857]
It looks like the hotlinks in our markdown files may not be rendering correctly - possibly there has been a change on the github side that has caused this?
For instance, see the CONTRIBUTING.md file at the top level
https://github.com/01org/cc-oci-runtime/blob/master/CONTRIBUTING.md
where you can see links showing (in the cooked view) as:
```
[GPL v2 License] (https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)
```
where the (xxx) part should not be rendered at all, and the []'s should also vanish etc.

**Comment by jodh-intel** [comment]
We probably want to raise this on github itself?

**Comment by dlespiau** [comment]
There's a space between `]` and `(`!

**Comment by grahamwhaley** [comment]
Good spot! - let me fix that (and then see if we have others elsewhere as well)

**Comment by grahamwhaley** [comment]
For ref - the only other instance a grep turned up was here:
https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Fedora-25.md#increase-limits-optional
