### ISSUE TITLE
cc-oci-runtime: Does not compile on FC24

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#887]
./autogen.sh
configure.ac:43: error: Please install autoconf-archive version ${autoconf_archive_version}
configure.ac:38: MACRO_CHECK is expanded from...
configure.ac:43: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by mcastelino** [comment]
And also on Ubuntu

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

./autogen.sh
configure.ac:43: error: Please install autoconf-archive version ${autoconf_archive_version}
configure.ac:38: MACRO_CHECK is expanded from...
configure.ac:43: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by sameo** [comment]
Same issue on FC25

**Comment by amshinde** [comment]
Related to commit: 
https://github.com/01org/cc-oci-runtime/pull/841/files#diff-bcae78d96781b13bf09dc35547ac038cR30

**Comment by gorozco1** [comment]
@mcastelino @sameo This is due: https://github.com/01org/cc-oci-runtime#dependencies 
introduced a new requirement: `autoconf-archive - version 2017.03.21 or above`
It can be solved in latest releases of ubuntu and fedora (Ubuntu 17.04 and Fedora 25) installing autoconf-archive.

However older releases cannot fulfil the requirement.

**Comment by gorozco1** [comment]
Related to #888 and fixed for F24

**Comment by grahamwhaley** [comment]
Also related to https://github.com/01org/cc-oci-runtime/issues/875 where I posted an interim helper-fix for developers https://github.com/01org/cc-oci-runtime/pull/876

**Comment by dlespiau** [comment]
It would be better if, to build the project, we don't have to ask people to install a package from a repo that is not part of the usual distro repositories. That's yet another hurdle to go through and we already have enough of them I'm afraid.

**Comment by gorozco1** [comment]
@dlespiau this is only to build  `cc-oci-runtime` not for using it.

**Comment by jcvenegas** [comment]
So our configure is failing because we are misssing this m4 files.

1.- Lets disable valgrind and code coverga if the m4 files are not installed, and let the user at least build cc-oci-runtime without this unusual depedency.

2.- For people that still want to use valgrind with 'make check' lets add a way to download the m4 files (like #876 )

@amshinde  @jodh-intel  @dlespiau  any comments ?

**Comment by dlespiau** [comment]
The whole thing has caused quite some pain. I wish we could just revert the change instead of having to work around the limitations of a tool.

**Comment by gorozco1** [comment]
Fixed with #911
