### ISSUE TITLE
Need to be able to build and install Clear Containers from source

### ISSUE THREAD

**Issue by egernst** [01org/cc-oci-runtime#912]
If a user  pulls down cc-oci-runtime and does a make install, Clear Containers will not work.  It is assumed that binary artifacts area already installed.

We need to create an option to build all of the relevant parts for Clear Containers from source.  This build will initially take a long time, but without this usability for Clear Containers is very poor.  We need to allow developers to be able to rebuild a given release in its entirety from source, including things like the kernel and container image.

This will solve problems like: https://github.com/01org/cc-oci-runtime/issues/769

**Comment by gorozco1** [comment]
Building the kernel and container image from source is out of scope to fix this issue, what we are going to do is to provide the user in the doc the dependencies needed to run clear-containers. 

We'll provide the scripts to do so, and will configure will fail if the "dependencies" are not meet.

**Comment by egernst** [comment]
Ultimately, people will need the ability to easily modify the kernel as well.  I can call that a P3, perhaps, though.

Having said that, I think it's still a high priority to added a make option called something like "make install-complete" which would do the pull and installation of .img/kernel.

**Comment by gorozco1** [comment]
@egernst  agreed 👍 

just created two other items to build from source the components.

**Comment by jcvenegas** [comment]
@egernst  what about qemu-lite this is something we should not care in `make install-complete`
