### ISSUE TITLE
installation guide for centOS appears stale

### ISSUE THREAD

**Issue by egernst** [01org/cc-oci-runtime#926]
Installation guide for centos still references checking out runtime 2.1.0.  Can / should this be updated to latest?

**Comment by egernst** [comment]
@jcvenegas  @chavafg @GabyCT

**Comment by GabyCT** [comment]
@egernst, I will work on this

**Comment by GabyCT** [comment]
@gorozco1 we need the obs packages for centos as this ones
http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-staging/CentOS_7/x86_64/ are not for 2.1.9.

@egernst when @gorozco1 updates the repository with the obs package I can update the documentation

**Comment by GabyCT** [comment]
@gorozco1 I just saw the latest obs packages thanks
