### ISSUE TITLE
Change release process check list

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#937]
Change release process, instead create a release candidate we can test the HEAD what will  be the last commit using new autoamted obs package generation we can generate and test commits   based on HEAD.

- [ ] Test the HEAD commit of the master branch using the tests included in the source code within the ```tests/``` directory.
- [ ] Run Coverity Scan on HEAD commit and ensure no medium or high severity issues are reported.
- [ ] Update ```versions.txt``` with package versions used by the release and the cc-oci-runtime.
- [ ] Generate OBS packages based on HEAD.
- [ ] Test OBS packages
	- [ ] Manual tests
		- [ ] Installation test.
		- [ ] Package signature test.
	- [ ] Automated tests
		- [ ] Integration tests included in the source code under the tests/integration directory.
- [ ] Update ```configure.ac``` with the ```cc-oci-runtime``` version tagged.
- [ ] Tag release using new version.
- [ ] Write release notes:
  - [ ] Brief summary of known issues, pointing to the appropriate Issues/PRs.
  - [ ] Version of Docker (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of the OCI spec (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of Clear Container image used by the release.
  - [ ] Add links to Installation instructions.
  - [ ] Document any common vulnerabilities and exposures (CVEs) fixed with links to the CVE database.
- [ ] Post release details on the public mailing list.
- [ ] Update public IRC channel with a link to the latest release.

**Comment by jcvenegas** [comment]
@devimc @gorozco1  @jodh-intel can you review this chagnes to the release process ?

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
For reference, `diff`-ing the proposed process above with the current one [*] gives:

```
$ sdiff --suppress-common-lines --width=$COLUMNS current.txt proposed.txt
- [ ] Tag and release as a release candidate the HEAD commit of the master.                   <
- [ ] Generate OBS packages using latest public release candidate.                            | - [ ] Generate OBS packages based on HEAD.
- [ ] Tag release using the same commit of the latest release candidate.                      | - [ ] Tag release using the same HEAD packaged.
```
@gorozco1, @sameo, @dlespiau, @grahamwhaley - do you have any thoughts?

lgtm.

---
[*] - https://github.com/01org/cc-oci-runtime/wiki/Release-Checklist

**Comment by gorozco1** [comment]
@jcvenegas  please

**Move:**

- [ ] Update ```configure.ac``` with the ```cc-oci-runtime``` version tagged.

**From**
- [ ] Update ```configure.ac``` with the ```cc-oci-runtime``` version tagged.
- [ ] Generate OBS packages based on HEAD.

**To** 
- [ ] Tag release using the same HEAD packaged.
- [ ] Update ```configure.ac``` with the ```cc-oci-runtime``` version tagged.

**Comment by jcvenegas** [comment]
@gorozco1  done

**Comment by jcvenegas** [comment]
Changed in wiki
- [ ] Test the HEAD commit of the master branch using the tests included in the source code within the ```tests/``` directory.
- [ ] Run Coverity Scan on HEAD commit and ensure no medium or high severity issues are reported.
- [ ] Tag and release as a release candidate the HEAD commit of the master.
- [ ] Update ```versions.txt``` with package versions used by the release and the cc-oci-runtime.
- [ ] Update ```configure.ac``` with the ```cc-oci-runtime``` version tagged.
- [ ] Generate OBS packages using latest public release candidate.
- [ ] Test OBS packages
	- [ ] Manual tests
		- [ ] Installation test.
		- [ ] Package signature test.
	- [ ] Automated tests
		- [ ] Integration tests included in the source code under the tests/integration directory.
- [ ] Tag release using the same commit of the latest release candidate.
- [ ] Write release notes:
  - [ ] Brief summary of known issues, pointing to the appropriate Issues/PRs.
  - [ ] Version of Docker (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of the OCI spec (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of Clear Container image used by the release.
  - [ ] Add links to Installation instructions.
  - [ ] Document any common vulnerabilities and exposures (CVEs) fixed with links to the CVE database.
- [ ] Post release details on the public mailing list.
- [ ] Update public IRC channel with a link to the latest release.
