### ISSUE TITLE
swarm test hangs in docker 17

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#938]
The test related with swarm (nds, mut, swarm) hangs in docker 17 two things has to be done:
- [ ] the test  should fail after a timeout to not block the execution.
- [ ] skip test if docker 1.12 is not being used

**Comment by jcvenegas** [comment]
@GabyCT  @chavafg is it ok to skip those test ? in docker 17 or it is just my environment ?

**Comment by chavafg** [comment]
That is expected behavior, the issue is documented on #854

**Comment by jcvenegas** [comment]
@chavafg docker swarm is working for me. I sent a PR to fix the tests. Could you confirm all works like 1.12.1 ? 
If it works we will need to update our wiki:
https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Ubuntu.md#option-1-docker-1121-compatible-with-swarm
