### ISSUE TITLE
test-pmd DPDK workload fails

### ISSUE THREAD

**Issue by egernst** [01org/cc-oci-runtime#949]
When running test PMD in standard clear container, it fails.  If I run using a direct mounted filesystem, it succeeds without issue.

For details on reproducing this failure, see https://gist.github.com/egernst/e12a0446e2482c270acb47dbca065e99

**Comment by rarindam** [comment]
open("/var/run/.rte_config", O_RDWR|O_CREAT, 0660) = 3
ftruncate(3, 208420)                    = 0
fcntl(3, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=28, l_len=11264}) = 0
mmap(NULL, 208420, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = -1 EINVAL (Invalid argument)
write(2, "PANIC in rte_eal_config_create()"..., 34PANIC in rte_eal_config_create():
) = 34
write(2, "Cannot mmap memory for rte_confi"..., 34Cannot mmap memory for rte_config
) = 34

**Comment by egernst** [comment]
This looks familiar.  In the past, I bind-mounted that to /tmp and edited code to look their, and it continued and then failed on the next file...

If you look at the filesystem, you should find /var/run/.rte_config, right?

**Comment by rarindam** [comment]
The file is there.
I am looking at setlock which is a doubt here.
Ftruncate works fine.

**Comment by egernst** [comment]
any updates @rarindam ?

**Comment by rarindam** [comment]
Hi Eric,
Currently we are trying to fix the issues in vhost-9p (hostsidein-kernel 9p server).
The xsetattribute feature is work in progress.
We will debug the issue with that feature implemented. This is to narrow down areas to concentrate.
Regards,
Arindam

**Comment by rarindam** [comment]
Hi Eric,
The crash does seem to happen due to mmap.
However, when I try to do mmap using our new vhost9p module, I dont see any issues.
But of course the filesizes are much sammler (6mb).
1. Is there anyway you can run the same dpdk setup on your host, instead of using the VM, or on a VM without the docker environment.
2. What can I do to replicate just the dpdk setup on a host.

Thanks,
Arindam

**Comment by egernst** [comment]
Arindam,

Yes, I used VM with DPDK installed for testing purposes successfully.  When we are both online I could send you this ubuntu img / qemu cmdline. 

As for on host - of course. Most straight forward may be to follow what I did for setting up the container image. This is described at https://gist.github.com/egernst/04c3576133ec5d7e2ae390fee4265c71

**Comment by rarindam** [comment]
Hi Eric,
I was able to setup the following environment, and see no crash:
1. testpmd running on a /tmp folder which is mounted using 9p virtio, which any containers.

2a. From /tmp, if I run ./dpdk/build/build/app/test-pmd/testpmd -- -i
      I get the crash. Attached crash dump.
[log.txt](https://github.com/01org/cc-oci-runtime/files/1149811/log.txt)


2b. From /tmp, if I run ./dpdk/x86_64-native-linuxapp-gcc/app/testppd -- -i, everything works  fine.
      I get the command prompt from testpmd. Everyhitng works fine.
      Attached log:
[Pass_log.txt](https://github.com/01org/cc-oci-runtime/files/1149816/Pass_log.txt)

3. Can you conform if you see the same result in your container?
4. x86_64-native-linuxapp-gcc is generated insode DPDK when I do 
   make T=x86_64-native-linuxapp-gcc. I then copy paste the whole dpdk folder to the tmp folder and run from there.

Regards,
Arindam

**Comment by rarindam** [comment]
Okay,
Figured out the root cause:
1. By default, 9pfs provides readonly mmap. Meaninig:
    open("/tmp/.rte_config", O_RDWR|O_CREAT, 0660) with RDWR flag, and then a consequent mmap with any value will fail.
    Reason: `generic_file_readonly_mmap` is used by 9pfs Kernel side client code, in case there is no caching.

2. How to avoid this:
    For Guest OS, ensure CONFIG_9P_FSCACHE is enable.
    Everything else remaining the same, the mount command in the guest OS should looks something like this:
   mount -t 9p -o trans=virtio test_mount /tmp/shared/ -oversion=9p2000.L,posixacl,cache=[loose or mmap or fscache]
   Then instead of  `generic_file_readonly_mmap`, `v9fs_file_mmap` is used, which allows mmaping with write capabilities.

3. @egernst , can you try that out in your setup? Mine is cleaned up.
Arindam

**Comment by egernst** [comment]
@rarindam -- I've waited shamefully long but finally tested this today, though on 3.0 (clearcontainers/runtime).

In my testing, I'm seeing the testpmd start up without issue when making the mount command changes, regardless of whether the FSCACHE is enabled or not in the guest's kernel config.  Can you comment on this?

**Comment by egernst** [comment]
Also, I'd like a better understanding of *why* caching is required here (I would've thought this would be just a performant change, not necessarily a permissions / access change).  Thanks.

**Comment by egernst** [comment]
Also, why virtio version 9p2000.L?
Why posix ACL?

**Comment by egernst** [comment]
FYI, I ran some FIO tests this morning, and see that mmap has slightly better performance relative to fscache; I plan to use this cache option instead.

**Comment by egernst** [comment]
I don't foresee this being fixed on 2.1.  

Being addressed by 9p mount fails for certain workloads #92 on 3.0
