### ISSUE TITLE
Networking: systemd error message on container launch

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#96]
The following message shows up on container launch even though the hostname is setup correctly 

[    0.076952] systemd[1]: Failed to initialise default hostname

sudo docker-upstream run -it debian
[    0.076952] systemd[1]: Failed to initialise default hostname
root@c897841142fe:/# hostname
c897841142fe

**Comment by jodh-intel** [comment]
This is a duplicate of #84.
