### ISSUE TITLE
Update Kernel config and release version

### ISSUE THREAD

**Issue by miguelinux** [01org/cc-oci-runtime#994]
from @sboeuf email:

In order to get the new agent running properly inside the VM with a clear-containers image, we need to enable 3 config flags to the clear containers kernel:

CONFIG_KEYS=y                                                                 
CONFIG_COMPAT=y                                                               
CONFIG_KEYS_COMPAT=y

**Comment by miguelinux** [comment]
This features in son hold, meanwhile @sboeuf do some PnP test.

**Comment by dlespiau** [comment]
No just PnP. I would:

 - Fix libcontainer to not require CONFIG_KEYS. If libcontainers needs this option just to clear the session keyring we should be able to make it work on kernels without that option enabled.
 - CONFIG_COMPAT (support for 32-bit user space) should not be enabled.

**Comment by sboeuf** [comment]
Some updates here:
We actually don't need CONFIG_COMPAT and CONFIG_KEYS_COMPAT, that was a mistake.
And about CONFIG_KEYS, it is only needed if we want this option to be enabled in our agent. As long as we disable this from the agent, we actually don't need any extra config :)
We can close this issue and there is no need to change the CC kernel config.
